// SPDX-FileCopyrightText: © 2025-2026 Andreas Wendleder
// SPDX-License-Identifier: Apache-2.0

#ifndef BORG_MATH_H
#define BORG_MATH_H

#include <stdint.h>

/**
 * FP16 sin/cos using a 64-entry lookup table.
 * Angle is in FP16 radians [0, 2π).
 * Accuracy: matches FP16 precision (~3.3 digits).
 */

// Negate FP16 value (XOR sign bit)
static inline uint16_t fp16_neg(uint16_t x) {
    return x ^ 0x8000;
}

// FP16 constants
#define FP16_ZERO     0x0000
#define FP16_ONE      0x3C00
#define FP16_PI       0x4248  // 3.14062
#define FP16_HALF_PI  0x3E48  // 1.57031
#define FP16_TWO_PI   0x4648  // 6.28125

// sin LUT: 65 entries for sin(i * π/128), i = 0..64
// Generated by numpy: int(np.float16(math.sin(i*pi/128)).view(np.uint16))
static const uint16_t sin_lut[65] = {
    0x0000, 0x2648, 0x2A48, 0x2CB5, 0x2E46, 0x2FD6, 0x30B2, 0x3179,
    0x323E, 0x3303, 0x33C6, 0x3444, 0x34A5, 0x3505, 0x3564, 0x35C2,
    0x361F, 0x367C, 0x36D7, 0x3732, 0x378B, 0x37E3, 0x381D, 0x3848,
    0x3872, 0x389B, 0x38C4, 0x38EC, 0x3913, 0x393A, 0x395F, 0x3984,
    0x39A8, 0x39CB, 0x39ED, 0x3A0F, 0x3A2F, 0x3A4F, 0x3A6D, 0x3A8A,
    0x3AA7, 0x3AC2, 0x3ADD, 0x3AF6, 0x3B0E, 0x3B25, 0x3B3B, 0x3B50,
    0x3B64, 0x3B77, 0x3B88, 0x3B99, 0x3BA8, 0x3BB6, 0x3BC3, 0x3BCE,
    0x3BD9, 0x3BE2, 0x3BEA, 0x3BF1, 0x3BF6, 0x3BFA, 0x3BFE, 0x3BFF,
    0x3C00,
};

/** Compute FP16 sin(angle) where angle is FP16 radians. */
uint16_t fp16_sin(uint16_t angle_fp16);

/** Compute FP16 cos(angle) = sin(angle + π/2). */
uint16_t fp16_cos(uint16_t angle_fp16);

#endif // BORG_MATH_H
