// Generated by CIRCT firtool-1.140.0
`ifndef layers_tt_um_tt_tinyQV_Verification_Assert
  `define layers_tt_um_tt_tinyQV_Verification_Assert
  `include "layers-tt_um_tt_tinyQV-Verification.sv"
`endif // not def layers_tt_um_tt_tinyQV_Verification_Assert
