version = 3.10.4
runner.dialect = scala213
fileOverride {
  "glob:**/tinyqv/src/**" {
     runner.dialect = scala3
  }
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/borg/package.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/borg/src/**" {
     runner.dialect = scala3
  }
  "glob:**/.bsp/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  "glob:**/tinyqv/package.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/tinyqv/test/src/**" {
     runner.dialect = scala3
  }
  "glob:**/borg/test/src/**" {
runner.dialect = scala3
  }
}
