#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Andreas Wendleder
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate librelane/generated_sources.yaml's VERILOG_FILES list from
out/hardware/borg/verilog_wafer/wafer_files.txt, produced by
`make generate_verilog_wafer` (mill asic.tt.runMain asic.tt.BorgOnlyMain).

Replaces a hand-maintained VERILOG_FILES list that already drifted out of
sync once for real: it still listed Hutt.sv/Peripherals.sv/QspiBackend.sv/
uart_*.sv (BorgOnlyTop has no Hutt/SoCLogic, so none of those exist in this
target's output), and had to be patched by hand for the rgbzMem ->
rgbzMems rename when MSAA's per-sample tile buffer landed. Re-run this
script (make generated-sources, or it runs automatically as part of
`make librelane`) any time BorgOnlyTop's module set changes instead of
hand-editing the list again.

Usage (from asic/wafer.space/):
    python3 scripts/gen_librelane_sources.py
"""
import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
WAFER_SPACE_DIR = SCRIPT_DIR.parent
REPO_ROOT = WAFER_SPACE_DIR.parent.parent
WAFER_FILES_TXT = REPO_ROOT / "out/hardware/borg/verilog_wafer/wafer_files.txt"
OUT_YAML = WAFER_SPACE_DIR / "librelane/generated_sources.yaml"


def main() -> None:
    if not WAFER_FILES_TXT.exists():
        sys.exit(
            f"{WAFER_FILES_TXT} not found -- run `make generate_verilog_wafer` "
            "(top-level Makefile) first."
        )

    names = sorted(
        pathlib.Path(line.strip()).name
        for line in WAFER_FILES_TXT.read_text().splitlines()
        if line.strip()
    )
    if not names:
        sys.exit(f"{WAFER_FILES_TXT} is empty -- nothing to generate sources for.")

    lines = [
        "# Generated by scripts/gen_librelane_sources.py from",
        "# out/hardware/borg/verilog_wafer/wafer_files.txt -- do not hand-edit;",
        "# re-run the script (or `make librelane`, which runs it automatically)",
        "# after any BorgOnlyTop RTL change that adds/removes/renames a module.",
        "VERILOG_FILES:",
        "- dir::../src/chip_top.sv",
        "- dir::../src/chip_core.sv",
    ]
    lines += [f"- dir::../../../out/hardware/borg/verilog_wafer/{n}" for n in names]

    OUT_YAML.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_YAML} ({len(names)} generated + 2 hand-written source files)")


if __name__ == "__main__":
    main()
