#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Andreas Wendleder
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate librelane/generated_sources.yaml's VERILOG_FILES list from
out/hardware/borg/verilog_wafer/wafer_files.txt, produced by
`make generate_verilog_wafer` (mill asic.tt.runMain asic.tt.BorgOnlyMain).

Replaces a hand-maintained VERILOG_FILES list that already drifted out of
sync once for real: it still listed Hutt.sv/Peripherals.sv/QspiBackend.sv/
uart_*.sv (BorgOnlyTop has no Hutt/SoCLogic, so none of those exist in this
target's output), and had to be patched by hand for the rgbzMem ->
rgbzMems rename when MSAA's per-sample tile buffer landed. Re-run this
script (make generated-sources, or it runs automatically as part of
`make librelane`) any time BorgOnlyTop's module set changes instead of
hand-editing the list again.

The slot argument selects which BorgOnlyTop emission to list. The two slots
have different pad maps (46 bidir + 4 input vs 40 + 12) and are emitted to
separate directories, because both produce a module named `BorgOnlyTop` --
mixing them in one directory would be silently wrong.

Usage (from asic/wafer.space/):
    python3 scripts/gen_librelane_sources.py [1x0p5|1x1]
"""
import pathlib
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
WAFER_SPACE_DIR = SCRIPT_DIR.parent
REPO_ROOT = WAFER_SPACE_DIR.parent.parent

# slot -> (emission subdir, make target that produces it)
SLOTS = {
    "1x0p5": ("verilog_wafer", "generate_verilog_wafer"),
    "1x1": ("verilog_wafer_1x1", "generate_verilog_wafer_1x1"),
}
OUT_YAML = WAFER_SPACE_DIR / "librelane/generated_sources.yaml"


def main() -> None:
    slot = sys.argv[1] if len(sys.argv) > 1 else "1x0p5"
    if slot not in SLOTS:
        sys.exit(f"unknown slot {slot!r} -- expected one of {sorted(SLOTS)}")
    subdir, make_target = SLOTS[slot]
    wafer_files_txt = REPO_ROOT / f"out/hardware/borg/{subdir}/wafer_files.txt"

    if not wafer_files_txt.exists():
        sys.exit(
            f"{wafer_files_txt} not found -- run `make {make_target}` "
            "(top-level Makefile) first."
        )

    names = sorted(
        pathlib.Path(line.strip()).name
        for line in wafer_files_txt.read_text().splitlines()
        if line.strip()
    )
    if not names:
        sys.exit(f"{wafer_files_txt} is empty -- nothing to generate sources for.")

    lines = [
        "# Generated by scripts/gen_librelane_sources.py from",
        f"# out/hardware/borg/{subdir}/wafer_files.txt (SLOT={slot}) -- do not",
        "# hand-edit; re-run the script (or `make librelane`, which runs it",
        "# automatically) after any BorgOnlyTop RTL change that adds/removes/",
        "# renames a module, or after switching SLOT.",
        "VERILOG_FILES:",
        "- dir::../src/chip_top.sv",
        "- dir::../src/chip_core.sv",
    ]
    lines += [f"- dir::../../../out/hardware/borg/{subdir}/{n}" for n in names]

    OUT_YAML.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_YAML} for SLOT={slot} "
          f"({len(names)} generated + 2 hand-written source files)")


if __name__ == "__main__":
    main()
