// Generated by CIRCT firtool-1.140.0
module AddRecFN(
  input  [32:0] io_a,
                io_b,
  output [32:0] io_out
);

  wire        _addRawFN_io_invalidExc;
  wire        _addRawFN_io_rawOut_isNaN;
  wire        _addRawFN_io_rawOut_isInf;
  wire        _addRawFN_io_rawOut_isZero;
  wire        _addRawFN_io_rawOut_sign;
  wire [9:0]  _addRawFN_io_rawOut_sExp;
  wire [26:0] _addRawFN_io_rawOut_sig;
  AddRawFN addRawFN (
    .io_a_isNaN       ((&(io_a[31:30])) & io_a[29]),
    .io_a_isInf       ((&(io_a[31:30])) & ~(io_a[29])),
    .io_a_isZero      (~(|(io_a[31:29]))),
    .io_a_sign        (io_a[32]),
    .io_a_sExp        ({1'h0, io_a[31:23]}),
    .io_a_sig         ({1'h0, |(io_a[31:29]), io_a[22:0]}),
    .io_b_isNaN       ((&(io_b[31:30])) & io_b[29]),
    .io_b_isInf       ((&(io_b[31:30])) & ~(io_b[29])),
    .io_b_isZero      (~(|(io_b[31:29]))),
    .io_b_sign        (io_b[32]),
    .io_b_sExp        ({1'h0, io_b[31:23]}),
    .io_b_sig         ({1'h0, |(io_b[31:29]), io_b[22:0]}),
    .io_invalidExc    (_addRawFN_io_invalidExc),
    .io_rawOut_isNaN  (_addRawFN_io_rawOut_isNaN),
    .io_rawOut_isInf  (_addRawFN_io_rawOut_isInf),
    .io_rawOut_isZero (_addRawFN_io_rawOut_isZero),
    .io_rawOut_sign   (_addRawFN_io_rawOut_sign),
    .io_rawOut_sExp   (_addRawFN_io_rawOut_sExp),
    .io_rawOut_sig    (_addRawFN_io_rawOut_sig)
  );
  RoundRawFNToRecFN_e8_s24 roundRawFNToRecFN (
    .io_invalidExc (_addRawFN_io_invalidExc),
    .io_in_isNaN   (_addRawFN_io_rawOut_isNaN),
    .io_in_isInf   (_addRawFN_io_rawOut_isInf),
    .io_in_isZero  (_addRawFN_io_rawOut_isZero),
    .io_in_sign    (_addRawFN_io_rawOut_sign),
    .io_in_sExp    (_addRawFN_io_rawOut_sExp),
    .io_in_sig     (_addRawFN_io_rawOut_sig),
    .io_out        (io_out)
  );
endmodule

