// Generated by CIRCT firtool-1.140.0
module AddRawFN(
  input         io_a_isNaN,
                io_a_isInf,
                io_a_isZero,
                io_a_sign,
  input  [9:0]  io_a_sExp,
  input  [24:0] io_a_sig,
  input         io_b_isNaN,
                io_b_isInf,
                io_b_isZero,
                io_b_sign,
  input  [9:0]  io_b_sExp,
  input  [24:0] io_b_sig,
  output        io_invalidExc,
                io_rawOut_isNaN,
                io_rawOut_isInf,
                io_rawOut_isZero,
                io_rawOut_sign,
  output [9:0]  io_rawOut_sExp,
  output [26:0] io_rawOut_sig
);

  wire [9:0]  _sDiffExps_T = io_a_sExp - io_b_sExp;
  wire        _common_sExpOut_T = $signed(_sDiffExps_T) < 10'sh0;
  wire [4:0]  _modNatAlignDist_T_4 =
    _common_sExpOut_T ? io_b_sExp[4:0] - io_a_sExp[4:0] : _sDiffExps_T[4:0];
  wire        isMaxAlign =
    (|(_sDiffExps_T[9:5])) & (_sDiffExps_T[9:5] != 5'h1F | _sDiffExps_T[4:0] == 5'h0);
  wire [4:0]  alignDist = isMaxAlign ? 5'h1F : _modNatAlignDist_T_4;
  wire        far_subMags = io_a_sign != io_b_sign;
  wire        closeSubMags = far_subMags & ~isMaxAlign & _modNatAlignDist_T_4 < 5'h2;
  wire        _close_alignedSigA_T_5 = $signed(_sDiffExps_T) > -10'sh1;
  wire [26:0] _close_alignedSigA_T_4 =
    _close_alignedSigA_T_5 & _sDiffExps_T[0] ? {io_a_sig, 2'h0} : 27'h0;
  wire [25:0] _GEN =
    _close_alignedSigA_T_4[25:0]
    | (_close_alignedSigA_T_5 & ~(_sDiffExps_T[0]) ? {io_a_sig, 1'h0} : 26'h0);
  wire [26:0] _close_sSigSum_T_3 =
    {_close_alignedSigA_T_4[26],
     _GEN[25],
     _GEN[24:0] | (_common_sExpOut_T ? io_a_sig : 25'h0)}
    - {io_b_sig[24], io_b_sig, 1'h0};
  wire        _close_notTotalCancellation_signOut_T =
    $signed(_close_sSigSum_T_3) < 27'sh0;
  wire [25:0] _close_sigSum_T_4 =
    _close_notTotalCancellation_signOut_T
      ? 26'h0 - _close_sSigSum_T_3[25:0]
      : _close_sSigSum_T_3[25:0];
  wire [3:0]  close_normDistReduced2 =
    (|(_close_sigSum_T_4[25:24]))
      ? 4'h0
      : (|(_close_sigSum_T_4[23:22]))
          ? 4'h1
          : (|(_close_sigSum_T_4[21:20]))
              ? 4'h2
              : (|(_close_sigSum_T_4[19:18]))
                  ? 4'h3
                  : (|(_close_sigSum_T_4[17:16]))
                      ? 4'h4
                      : (|(_close_sigSum_T_4[15:14]))
                          ? 4'h5
                          : (|(_close_sigSum_T_4[13:12]))
                              ? 4'h6
                              : (|(_close_sigSum_T_4[11:10]))
                                  ? 4'h7
                                  : (|(_close_sigSum_T_4[9:8]))
                                      ? 4'h8
                                      : (|(_close_sigSum_T_4[7:6]))
                                          ? 4'h9
                                          : (|(_close_sigSum_T_4[5:4]))
                                              ? 4'hA
                                              : (|(_close_sigSum_T_4[3:2])) ? 4'hB : 4'hC;
  wire [56:0] _close_sigOut_T =
    {31'h0, _close_sigSum_T_4} << {52'h0, close_normDistReduced2, 1'h0};
  wire [23:0] _far_sigSmaller_T_1 = _common_sExpOut_T ? io_a_sig[23:0] : io_b_sig[23:0];
  wire [28:0] far_mainAlignedSigSmaller = {_far_sigSmaller_T_1, 5'h0} >> alignDist;
  wire [8:0]  far_roundExtraMask_shift = $unsigned($signed(9'sh100 >>> alignDist[4:2]));
  wire [9:0]  _GEN_0 =
    {far_mainAlignedSigSmaller[2:0],
     {|(_far_sigSmaller_T_1[23:22]),
      |(_far_sigSmaller_T_1[21:18]),
      |(_far_sigSmaller_T_1[17:14]),
      |(_far_sigSmaller_T_1[13:10]),
      |(_far_sigSmaller_T_1[9:6]),
      |(_far_sigSmaller_T_1[5:2]),
      |(_far_sigSmaller_T_1[1:0])}
       & {far_roundExtraMask_shift[1],
          far_roundExtraMask_shift[2],
          far_roundExtraMask_shift[3],
          far_roundExtraMask_shift[4],
          far_roundExtraMask_shift[5],
          far_roundExtraMask_shift[6],
          far_roundExtraMask_shift[7]}};
  wire        _GEN_1 = io_a_sign == io_b_sign;
  wire [27:0] _far_sigSum_T_3 =
    {1'h0, _common_sExpOut_T ? io_b_sig[23:0] : io_a_sig[23:0], 3'h0}
    + (_GEN_1
         ? {1'h0, far_mainAlignedSigSmaller[28:3], |_GEN_0}
         : {1'h1, ~{far_mainAlignedSigSmaller[28:3], |_GEN_0}}) + {27'h0, far_subMags};
  wire        notNaN_isInfOut = io_a_isInf | io_b_isInf;
  wire        addZeros = io_a_isZero & io_b_isZero;
  wire        notNaN_specialCase = notNaN_isInfOut | addZeros;
  assign io_invalidExc =
    io_a_isNaN & ~(io_a_sig[22]) | io_b_isNaN & ~(io_b_sig[22]) | io_a_isInf & io_b_isInf
    & far_subMags;
  assign io_rawOut_isNaN = io_a_isNaN | io_b_isNaN;
  assign io_rawOut_isInf = notNaN_isInfOut;
  assign io_rawOut_isZero =
    addZeros | ~notNaN_isInfOut & closeSubMags & ~(|(_close_sigOut_T[25:24]));
  assign io_rawOut_sign =
    io_a_sign == io_b_sign & io_a_sign | io_a_isInf & io_a_sign | io_b_isInf & io_b_sign
    | ~notNaN_specialCase & closeSubMags & (|(_close_sigOut_T[25:24]))
    & (io_a_sign ^ _close_notTotalCancellation_signOut_T) | ~notNaN_specialCase
    & ~closeSubMags & (_common_sExpOut_T ? io_b_sign : io_a_sign);
  assign io_rawOut_sExp =
    (closeSubMags | _common_sExpOut_T ? io_b_sExp : io_a_sExp)
    - {5'h0, closeSubMags ? {close_normDistReduced2, 1'h0} : {4'h0, far_subMags}};
  assign io_rawOut_sig =
    closeSubMags
      ? {_close_sigOut_T[25:0], 1'h0}
      : _GEN_1
          ? {_far_sigSum_T_3[27:2], _far_sigSum_T_3[1] | _far_sigSum_T_3[0]}
          : _far_sigSum_T_3[26:0];
endmodule

