// Generated by CIRCT firtool-1.140.0
module Borg(
  input         clock,
                reset,
  input  [5:0]  io_address,
  input  [31:0] io_data_in,
  input  [1:0]  io_data_write_n,
                io_data_read_n,
  output [31:0] io_data_out,
  output        io_data_ready,
  input  [7:0]  io_ui_in,
  output [7:0]  io_uo_out,
  output        io_user_interrupt
);

  wire [32:0] _f_add_io_out;
  wire [31:0] _instructionMemory_ext_R0_data;
  wire [31:0] _registerFile_ext_R0_data;
  wire [31:0] _registerFile_ext_R1_data;
  wire [31:0] _registerFile_ext_R2_data;
  reg  [2:0]  programCounter;
  reg         running;
  reg  [2:0]  busy_counter;
  wire        is_writing = io_data_write_n == 2'h2;
  wire        is_reading = io_data_read_n == 2'h2;
  wire        _pipe_reg_write_T_1 = busy_counter == 3'h1;
  wire [2:0]  _programCounter_T = programCounter + 3'h1;
  wire        _mmio_reg_en_T_1 = busy_counter == 3'h0;
  wire        rs1_en =
    running & _mmio_reg_en_T_1 | (|busy_counter) & (|(busy_counter[2:1]));
  reg         rs1_en_del;
  wire [31:0] recA_raw = rs1_en_del ? _registerFile_ext_R1_data : 32'h0;
  wire        rs2_en =
    running & _mmio_reg_en_T_1 | (|busy_counter) & (|(busy_counter[2:1]));
  reg         rs2_en_del;
  wire [31:0] recB_raw = rs2_en_del ? _registerFile_ext_R0_data : 32'h0;
  wire        mmio_reg_en = ~running & _mmio_reg_en_T_1 & (is_reading | is_writing);
  reg         mmio_reg_en_del;
  wire        recA_rawIn_isZeroExpIn = recA_raw[30:23] == 8'h0;
  wire [4:0]  recA_rawIn_normDist =
    recA_raw[22]
      ? 5'h0
      : recA_raw[21]
          ? 5'h1
          : recA_raw[20]
              ? 5'h2
              : recA_raw[19]
                  ? 5'h3
                  : recA_raw[18]
                      ? 5'h4
                      : recA_raw[17]
                          ? 5'h5
                          : recA_raw[16]
                              ? 5'h6
                              : recA_raw[15]
                                  ? 5'h7
                                  : recA_raw[14]
                                      ? 5'h8
                                      : recA_raw[13]
                                          ? 5'h9
                                          : recA_raw[12]
                                              ? 5'hA
                                              : recA_raw[11]
                                                  ? 5'hB
                                                  : recA_raw[10]
                                                      ? 5'hC
                                                      : recA_raw[9]
                                                          ? 5'hD
                                                          : recA_raw[8]
                                                              ? 5'hE
                                                              : recA_raw[7]
                                                                  ? 5'hF
                                                                  : recA_raw[6]
                                                                      ? 5'h10
                                                                      : recA_raw[5]
                                                                          ? 5'h11
                                                                          : recA_raw[4]
                                                                              ? 5'h12
                                                                              : recA_raw[3]
                                                                                  ? 5'h13
                                                                                  : recA_raw[2]
                                                                                      ? 5'h14
                                                                                      : recA_raw[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;
  wire [53:0] _recA_rawIn_subnormFract_T = {31'h0, recA_raw[22:0]} << recA_rawIn_normDist;
  wire [8:0]  _recA_rawIn_adjustedExp_T_4 =
    (recA_rawIn_isZeroExpIn ? {4'hF, ~recA_rawIn_normDist} : {1'h0, recA_raw[30:23]})
    + {7'h20, recA_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _recA_T_1 =
    recA_rawIn_isZeroExpIn & ~(|(recA_raw[22:0]))
      ? 3'h0
      : _recA_rawIn_adjustedExp_T_4[8:6];
  wire        recB_rawIn_isZeroExpIn = recB_raw[30:23] == 8'h0;
  wire [4:0]  recB_rawIn_normDist =
    recB_raw[22]
      ? 5'h0
      : recB_raw[21]
          ? 5'h1
          : recB_raw[20]
              ? 5'h2
              : recB_raw[19]
                  ? 5'h3
                  : recB_raw[18]
                      ? 5'h4
                      : recB_raw[17]
                          ? 5'h5
                          : recB_raw[16]
                              ? 5'h6
                              : recB_raw[15]
                                  ? 5'h7
                                  : recB_raw[14]
                                      ? 5'h8
                                      : recB_raw[13]
                                          ? 5'h9
                                          : recB_raw[12]
                                              ? 5'hA
                                              : recB_raw[11]
                                                  ? 5'hB
                                                  : recB_raw[10]
                                                      ? 5'hC
                                                      : recB_raw[9]
                                                          ? 5'hD
                                                          : recB_raw[8]
                                                              ? 5'hE
                                                              : recB_raw[7]
                                                                  ? 5'hF
                                                                  : recB_raw[6]
                                                                      ? 5'h10
                                                                      : recB_raw[5]
                                                                          ? 5'h11
                                                                          : recB_raw[4]
                                                                              ? 5'h12
                                                                              : recB_raw[3]
                                                                                  ? 5'h13
                                                                                  : recB_raw[2]
                                                                                      ? 5'h14
                                                                                      : recB_raw[1]
                                                                                          ? 5'h15
                                                                                          : 5'h16;
  wire [53:0] _recB_rawIn_subnormFract_T = {31'h0, recB_raw[22:0]} << recB_rawIn_normDist;
  wire [8:0]  _recB_rawIn_adjustedExp_T_4 =
    (recB_rawIn_isZeroExpIn ? {4'hF, ~recB_rawIn_normDist} : {1'h0, recB_raw[30:23]})
    + {7'h20, recB_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]  _recB_T_1 =
    recB_rawIn_isZeroExpIn & ~(|(recB_raw[22:0]))
      ? 3'h0
      : _recB_rawIn_adjustedExp_T_4[8:6];
  wire        pipe_reg_write = running & (|busy_counter) & _pipe_reg_write_T_1;
  wire        reg_w_data_rawIn_isInf = (&(_f_add_io_out[31:30])) & ~(_f_add_io_out[29]);
  wire        reg_w_data_isSubnormal = $signed({1'h0, _f_add_io_out[31:23]}) < 10'sh82;
  wire [23:0] _reg_w_data_denormFract_T_1 =
    {1'h0, |(_f_add_io_out[31:29]), _f_add_io_out[22:1]} >> 5'h1 - _f_add_io_out[27:23];
  reg  [5:0]  read_addr_del;
  reg         read_ready_del;
  wire        _GEN = running & _mmio_reg_en_T_1;
  wire        _GEN_0 = _instructionMemory_ext_R0_data == 32'h0;
  wire        _GEN_1 = ~(_GEN & _GEN_0) & running;
  wire        _GEN_2 = is_writing & io_address == 6'h3C;
  always @(posedge clock) begin
    if (reset) begin
      programCounter <= 3'h0;
      running <= 1'h0;
      busy_counter <= 3'h0;
      rs1_en_del <= 1'h0;
      rs2_en_del <= 1'h0;
      mmio_reg_en_del <= 1'h0;
      read_addr_del <= 6'h0;
      read_ready_del <= 1'h0;
    end
    else begin
      if (_GEN_2 & io_data_in[1]) begin
        programCounter <= 3'h0;
        busy_counter <= 3'h0;
      end
      else begin
        if (_GEN | ~((|busy_counter) & _pipe_reg_write_T_1)) begin
        end
        else
          programCounter <= _programCounter_T;
        if (_GEN) begin
          if (~_GEN_0)
            busy_counter <= 3'h4;
        end
        else if (|busy_counter)
          busy_counter <= busy_counter - 3'h1;
      end
      running <= _GEN_2 ? ~(io_data_in[1]) & (io_data_in[0] | _GEN_1) : _GEN_1;
      rs1_en_del <= rs1_en;
      rs2_en_del <= rs2_en;
      mmio_reg_en_del <= mmio_reg_en & is_reading;
      read_addr_del <= io_address;
      read_ready_del <= is_reading;
    end
  end // always @(posedge)
  registerFile_4x32 registerFile_ext (
    .R0_addr (_instructionMemory_ext_R0_data[21:20]),
    .R0_en   (rs2_en),
    .R0_clk  (clock),
    .R0_data (_registerFile_ext_R0_data),
    .R1_addr (_instructionMemory_ext_R0_data[16:15]),
    .R1_en   (rs1_en),
    .R1_clk  (clock),
    .R1_data (_registerFile_ext_R1_data),
    .R2_addr (io_address[3:2]),
    .R2_en   (mmio_reg_en),
    .R2_clk  (clock),
    .R2_data (_registerFile_ext_R2_data),
    .W0_addr (pipe_reg_write ? _instructionMemory_ext_R0_data[8:7] : io_address[3:2]),
    .W0_en   (is_writing & io_address < 6'h10 | pipe_reg_write),
    .W0_clk  (clock),
    .W0_data
      (pipe_reg_write
         ? {_f_add_io_out[32],
            (reg_w_data_isSubnormal ? 8'h0 : _f_add_io_out[30:23] + 8'h7F)
              | {8{(&(_f_add_io_out[31:30])) & _f_add_io_out[29]
                     | reg_w_data_rawIn_isInf}},
            reg_w_data_isSubnormal
              ? _reg_w_data_denormFract_T_1[22:0]
              : reg_w_data_rawIn_isInf ? 23'h0 : _f_add_io_out[22:0]}
         : io_data_in)
  );
  instructionMemory_4x32 instructionMemory_ext (
    .R0_addr
      ((|busy_counter) & _pipe_reg_write_T_1
         ? _programCounter_T[1:0]
         : programCounter[1:0]),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_instructionMemory_ext_R0_data),
    .W0_addr (io_address[3:2]),
    .W0_en   (is_writing & io_address[5] & io_address[5:4] != 2'h3),
    .W0_clk  (clock),
    .W0_data (io_data_in)
  );
  AddRecFN f_add (
    .io_a
      ({recA_raw[31],
        _recA_T_1[2:1],
        _recA_T_1[0] | (&(_recA_rawIn_adjustedExp_T_4[8:7])) & (|(recA_raw[22:0])),
        _recA_rawIn_adjustedExp_T_4[5:0],
        recA_rawIn_isZeroExpIn
          ? {_recA_rawIn_subnormFract_T[21:0], 1'h0}
          : recA_raw[22:0]}),
    .io_b
      ({recB_raw[31],
        _recB_T_1[2:1],
        _recB_T_1[0] | (&(_recB_rawIn_adjustedExp_T_4[8:7])) & (|(recB_raw[22:0])),
        _recB_rawIn_adjustedExp_T_4[5:0],
        recB_rawIn_isZeroExpIn
          ? {_recB_rawIn_subnormFract_T[21:0], 1'h0}
          : recB_raw[22:0]}),
    .io_out (_f_add_io_out)
  );
  assign io_data_out =
    read_addr_del == 6'h10
      ? {30'h0, ~running, 1'h0}
      : (read_addr_del == 6'hC | read_addr_del == 6'h8 | read_addr_del == 6'h4
         | read_addr_del == 6'h0) & mmio_reg_en_del
          ? _registerFile_ext_R2_data
          : 32'h0;
  assign io_data_ready = (&io_data_read_n) | read_ready_del;
  assign io_uo_out = 8'h0;
  assign io_user_interrupt = 1'h0;
endmodule

