// Generated by CIRCT firtool-1.137.0-1-gfcc42190a

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Borg(	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
  input         clock,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
                reset,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
  input  [5:0]  io_address,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [31:0] io_data_in,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [1:0]  io_data_write_n,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
                io_data_read_n,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output [31:0] io_data_out,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_data_ready,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  input  [7:0]  io_ui_in,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output [7:0]  io_uo_out,	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
  output        io_user_interrupt	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:7:16
);

  reg  [31:0] reg_value;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
  wire        is_writing = io_data_write_n == 2'h2;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :24:38
  reg  [31:0] result_to_read;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:34:33
  reg         read_ready;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:37:29
  always @(posedge clock) begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    if (reset)	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      reg_value <= 32'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
    else if (is_writing & io_address == 6'h0)	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:24:38, :28:{21,35}
      reg_value <= io_data_in;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28
    result_to_read <= reg_value + 32'h1;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:21:28, :34:{33,44}
    read_ready <= io_data_read_n == 2'h2;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :25:37, :37:29
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    initial begin	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        `INIT_RANDOM_PROLOG_	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        end	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
        reg_value = _RANDOM[2'h0];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :21:28
        result_to_read = _RANDOM[2'h1];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :34:33
        read_ready = _RANDOM[2'h2][0];	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :37:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
      `FIRRTL_AFTER_INITIAL	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_data_out = result_to_read;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :34:33
  assign io_data_ready = is_writing | read_ready;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :24:38, :37:29, :38:33
  assign io_uo_out = 8'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :43:15
  assign io_user_interrupt = 1'h0;	// home/gonsolo/work/borg_peripheral/borg/src/Borg.scala:6:7, :28:35
endmodule

