// Auto-generated by MmioMap.scala — do not edit manually
#pragma once

// --- System clock (from MmioMap.scala) ---
#define CLOCK_MHZ 4
#define UART_BAUD_DEFAULT 34  // 4 MHz / 115200 baud

// --- User UART peripheral ---
#define UART_TX     (*(volatile uint32_t *)0x08000200UL)
#define UART_STATUS (*(volatile uint32_t *)0x08000204UL)
#define UART_BAUD   (*(volatile uint32_t *)0x08000208UL)

// --- Borg GPU peripheral ---
#define BORG_BASE    0x08000300UL
#define BORG_REG(n)     (*(volatile uint32_t *)(BORG_BASE + (n) * 4))
#define BORG_IMEM(n)    (*(volatile uint32_t *)(BORG_BASE + 128 + (n) * 4))
#define BORG_CONTROL    (*(volatile uint32_t *)(BORG_BASE + 252))
#define BORG_STATUS     (*(volatile uint32_t *)(BORG_BASE + 252))
#define BORG_CTL_START  1  // write: start execution
#define BORG_CTL_RESET  2  // write: reset pipeline
#define BORG_STS_IDLE   2  // read: pipeline idle

// --- PSRAM (QSPI memory space) ---
#define PSRAM_IN(n)  (*(volatile uint32_t *)(0x01001000UL + (n) * 4))
#define PSRAM_OUT(n) (*(volatile uint32_t *)(0x01001000UL + 128 + (n) * 4))

// --- Convenience ---
#define STARTUP_DELAY() do { \
    for (volatile int i = 0; i < 10000; i++) ; \
  } while (0)

// --- Shared PSRAM layout (matches borg_mmio.py) ---
#define TEX_PSRAM_OFFSET 4200
#define DONE_MARKER 0xDEAD

// --- Borg instruction encoding (matches Borg.scala format) ---
// FP16: [15:14]=op [13:12]=rs3/ext [11:8]=rs2 [7:4]=rs1 [3:0]=rd
#define BORG_INSTR_FADD(rd, rs1, rs2)        (0x0000 | ((rs2) << 8) | ((rs1) << 4) | (rd))
#define BORG_INSTR_FMUL(rd, rs1, rs2)        (0x4000 | ((rs2) << 8) | ((rs1) << 4) | (rd))
#define BORG_INSTR_FMADD(rd, rs1, rs2, rs3)  (0x8000 | ((rs3) << 12) | ((rs2) << 8) | ((rs1) << 4) | (rd))
#define BORG_INSTR_HALT                       0x0000
