// SPDX-FileCopyrightText: © 2025-2026 Andreas Wendleder
// SPDX-License-Identifier: GPL-3.0-or-later

// Borg GPU driver — pipeline orchestration, hardware init, draw commands.

#include "borg_driver.h"
#include "borg_fpu.h"
#include "borg_raster.h"
#include "borg_math.h"
#include "borg_spirb.h"

// @doc:mmio-map
#include "borg_mmio.h"  // Auto-generated by MmioMap.scala
// @doc:end

#define FP16_SIXTEEN 0x4C00

static inline void fb_write_pixel(int base, rgb16_t c) {
  PSRAM_OUT(base + 0) = c.r;
  PSRAM_OUT(base + 1) = c.g;
  PSRAM_OUT(base + 2) = c.b;
}

static inline rgb16_t fb_read_texel(int base) {
  return (rgb16_t){ PSRAM_IN(base + 0), PSRAM_IN(base + 1), PSRAM_IN(base + 2) };
}

typedef struct { int w, h; } dim2_t;

typedef struct {
  int psram_offset;        // -1 = no texture
  dim2_t size;             // integer dimensions
  uint16_t w_fp16, h_fp16; // FP16 dimensions for Borg FPU
} texture_t;

// Runtime framebuffer dimensions and derived values
int borg_fb_width;
int borg_fb_height;
static fp16_t fp16_half_width;
static fp16_t pc_lut[BORG_MAX_FB_DIM];

#define NUM_VERTICES 3
#define MAX_CLIP_VERTS 4  // Clipping one triangle can produce at most a quad

// Clipped vertex: carries all interpolable attributes through clipping.
typedef struct {
    fp16_t x, y, z, w;      // clip-space position
    fp16_t r, g, b;          // vertex color
    fp16_t u, v;             // texture UV
} clip_vertex_t;

// Global timing vars
unsigned int t_init_cycles = 0;
unsigned int t_clear_cycles = 0;
unsigned int t_draw_cycles = 0;

// --- Texture state ---
static texture_t tex = { .psram_offset = -1 };

// --- UART ---
void putc_uart(int c) {
  while (UART_STATUS & 1)
    ;
  UART_TX = c;
}
static void puts_uart(const char *s) {
  while (*s)
    putc_uart(*s++);
}

// --- Timing and debug printing ---
static inline unsigned int get_cycles(void) {
  unsigned int cycles;
  __asm__ volatile ("csrr %0, cycle" : "=r" (cycles));
  return cycles;
}



// --- Shader globals ---
static spirb_shader_t vert_shader;
static spirb_shader_t rast_shader;
static spirb_shader_t frag_shader;

// --- Vertex shader ---
static void run_vertex_shader(const fp16_t *uniforms,
                               const fp16_t *attrs,
                               fp16_t *outputs) {
  const spirb_shader_t *s = &vert_shader;
  borg_load_spirb_shader(s);

  for (int i = 0; i < s->num_uniforms; i++)
    BORG_REG(s->uniform_regs[i]) = uniforms[i];

  for (int v = 0; v < NUM_VERTICES; v++) {
    BORG_CONTROL = BORG_CTL_RESET;
    for (int i = 0; i < s->num_uniforms; i++)
      BORG_REG(s->uniform_regs[i]) = uniforms[i];
    for (int i = 0; i < s->num_attributes; i++)
      BORG_REG(s->attribute_regs[i]) = attrs[v * s->num_attributes + i];
    for (int i = 0; i < s->num_consts; i++)
      BORG_REG(s->const_regs[i]) = s->const_vals[i];
    borg_run();
    for (int i = 0; i < s->num_outputs; i++)
      outputs[v * s->num_outputs + i] = BORG_REG(s->output_regs[i]) & 0xFFFF;
  }
}

// --- Public API ---

static inline uint32_t morton_interleave(uint32_t x) {
  x = (x | (x << 8)) & 0x00FF00FF;
  x = (x | (x << 4)) & 0x0F0F0F0F;
  x = (x | (x << 2)) & 0x33333333;
  x = (x | (x << 1)) & 0x55555555;
  return x;
}

static inline uint32_t morton_encode(uint32_t x, uint32_t y) {
  return morton_interleave(x) | (morton_interleave(y) << 1);
}

void borg_init(const BorgShaderModule *vert,
               const BorgShaderModule *rast,
               const BorgShaderModule *frag) {
  STARTUP_DELAY();
  UART_BAUD = UART_BAUD_DEFAULT;
  puts_uart("Borg pipeline\r\n");
  unsigned int t_init = get_cycles();

  // Read framebuffer dimensions from PSRAM (written by host)
  borg_fb_width  = PSRAM_IN(0) & 0xFFFF;
  borg_fb_height = PSRAM_IN(1) & 0xFFFF;
  if (borg_fb_width == 0 || borg_fb_width > BORG_MAX_FB_DIM) borg_fb_width = 16;
  if (borg_fb_height == 0 || borg_fb_height > BORG_MAX_FB_DIM) borg_fb_height = 16;

  // Compute FP16 half-width for NDC→screen transform
  // half_width = width / 2 (integer), then convert to FP16
  int hw = borg_fb_width / 2;
  // Simple integer-to-FP16 for powers of 2 (8, 16, 32)
  int exp = 0;
  int tmp = hw;
  while (tmp > 1) { tmp >>= 1; exp++; }
  fp16_half_width = ((exp + 15) << 10);  // power-of-2, mantissa=0

  // Compute pixel center LUT: 0.5, 1.5, ..., (width-0.5)
  fp16_t val = FP16_HALF;  // 0.5
  for (int i = 0; i < borg_fb_width; i++) {
    pc_lut[i] = val;
    val = borg_fp16_add(val, FP16_ONE);
  }

  spirb_parse(vert->code, &vert_shader);
  spirb_parse(rast->code, &rast_shader);
  spirb_parse(frag->code, &frag_shader);
  t_init_cycles = get_cycles() - t_init;
}

void borg_set_angle(borg_draw_data_t *d, fp16_t angle_fp16) {
  // Compute vertex shader uniforms from angle for Phase 2 4x4 Projection
  fp16_t s = fp16_sin(angle_fp16);
  fp16_t c = fp16_cos(angle_fp16);
  fp16_t ns = fp16_neg(s);
  
  // Col 0 (X)
  d->uniforms[0] = c;
  d->uniforms[1] = s;
  d->uniforms[2] = FP16_ZERO;
  d->uniforms[3] = FP16_ZERO;

  // Col 1 (Y)
  d->uniforms[4] = ns;
  d->uniforms[5] = c;
  d->uniforms[6] = FP16_ZERO;
  d->uniforms[7] = FP16_ZERO;

  // Col 2 (Z) - passed through seamlessly
  d->uniforms[8] = FP16_ZERO;
  d->uniforms[9] = FP16_ZERO;
  d->uniforms[10] = FP16_ONE;
  d->uniforms[11] = FP16_ZERO;

  // Col 3 (Translations/W)
  d->uniforms[12] = FP16_ZERO;
  d->uniforms[13] = FP16_ZERO;
  d->uniforms[14] = FP16_ZERO;
  d->uniforms[15] = FP16_ONE;
}

#define FRAME_FB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT * 3)  // RGB words
#define FRAME_ZB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT)        // Z-buffer words
#define FRAME_STRIDE  (FRAME_FB_SIZE + FRAME_ZB_SIZE + 1)     // FB + ZB + DONE marker

void borg_clear_zbuffer(int frame) {
  unsigned int t_start = get_cycles();
  int fb_offset = frame * FRAME_STRIDE;
  int zb_offset = fb_offset + FRAME_FB_SIZE;
  // Clear RGB framebuffer to black
  for (int i = 0; i < FRAME_FB_SIZE; i++)
    PSRAM_OUT(fb_offset + i) = 0;
  // Clear z-buffer to max depth
  for (int i = 0; i < FRAME_ZB_SIZE; i++)
    PSRAM_OUT(zb_offset + i) = FP16_MAX_DEPTH;
  t_clear_cycles = get_cycles() - t_start;
}

void borg_set_texture(int psram_offset, int width, int height) {
  tex = (texture_t){
    .psram_offset = psram_offset,
    .size = { width, height },
    .w_fp16 = uint_to_fp16(width), .h_fp16 = uint_to_fp16(height)
  };
}

void borg_clear_texture(void) {
  tex.psram_offset = -1;
}

static void shade_and_write_pixel(int frame, int px, int py,
                                  rgb16_t color, fp16_t z, uv16_t uv_interp,
                                  const texture_t *t) {
  // Depth test: read current z, compare (closer = smaller).
  // Skip pixels with negative Z (behind camera) — their sign bit would
  // corrupt the unsigned Z-buffer comparison.
  if (!fp16_ge_zero(z)) return;
  int zb_idx = frame * FRAME_STRIDE + FRAME_FB_SIZE + (py * BORG_FB_WIDTH + px);
  fp16_t old_z = PSRAM_OUT(zb_idx);
  if (z >= old_z) return;
  PSRAM_OUT(zb_idx) = z;

  // Texture sampling: replace vertex colors with texel
  if (t->psram_offset >= 0) {
    texcoord_t tc = uv_to_texcoord(uv_interp, t->w_fp16, t->h_fp16);
    if (tc.x >= t->size.w)  tc.x = t->size.w - 1;
    if (tc.y >= t->size.h) tc.y = t->size.h - 1;
    int morton_idx = morton_encode(tc.x, tc.y);
    int texel = t->psram_offset + morton_idx * 3;
    color = fb_read_texel(texel);
  }

  int base = frame * FRAME_STRIDE + (py * BORG_FB_WIDTH + px) * 3;
  fb_write_pixel(base, color);
}

// --- Triangle Clipping (Step 6) ---

// Linearly interpolate between two clip vertices: result = a + t * (b - a)
static clip_vertex_t clip_lerp(const clip_vertex_t *a, const clip_vertex_t *b, fp16_t t) {
  clip_vertex_t out;
  // For each component: out = a + t * (b - a) = fmadd(t, b-a, a)
  out.x = borg_fp16_fmadd(t, BORG_FP16_SUB(b->x, a->x), a->x);
  out.y = borg_fp16_fmadd(t, BORG_FP16_SUB(b->y, a->y), a->y);
  out.z = borg_fp16_fmadd(t, BORG_FP16_SUB(b->z, a->z), a->z);
  out.w = borg_fp16_fmadd(t, BORG_FP16_SUB(b->w, a->w), a->w);
  out.r = borg_fp16_fmadd(t, BORG_FP16_SUB(b->r, a->r), a->r);
  out.g = borg_fp16_fmadd(t, BORG_FP16_SUB(b->g, a->g), a->g);
  out.b = borg_fp16_fmadd(t, BORG_FP16_SUB(b->b, a->b), a->b);
  out.u = borg_fp16_fmadd(t, BORG_FP16_SUB(b->u, a->u), a->u);
  out.v = borg_fp16_fmadd(t, BORG_FP16_SUB(b->v, a->v), a->v);
  return out;
}

// Clip polygon against near plane (z >= 0 in clip space).
// Sutherland-Hodgman: vertices with z < 0 are outside.
// Returns number of output vertices (0..MAX_CLIP_VERTS).
static int clip_near(const clip_vertex_t *in, int n_in,
                     clip_vertex_t *out) {
  int n_out = 0;
  for (int i = 0; i < n_in; i++) {
    int prev_idx = (i == 0) ? n_in - 1 : i - 1;
    const clip_vertex_t *cur = &in[i];
    const clip_vertex_t *prev = &in[prev_idx];
    int cur_inside  = fp16_ge_zero(cur->z);
    int prev_inside = fp16_ge_zero(prev->z);
    if (cur_inside != prev_inside) {
      // Edge crosses the near plane — compute intersection.
      // t = prev.z / (prev.z - cur.z)
      fp16_t denom = BORG_FP16_SUB(prev->z, cur->z);
      fp16_t t = borg_fp16_mul(prev->z, borg_fp16_rcp(denom));
      out[n_out++] = clip_lerp(prev, cur, t);
    }
    if (cur_inside)
      out[n_out++] = *cur;
  }
  return n_out;
}

// Clip polygon against far plane (z <= w in clip space).
// Sutherland-Hodgman: vertices with z > w are outside.
// Returns number of output vertices (0..MAX_CLIP_VERTS+1, capped at 7 for a triangle).
static int clip_far(const clip_vertex_t *in, int n_in,
                    clip_vertex_t *out) {
  int n_out = 0;
  for (int i = 0; i < n_in; i++) {
    int prev_idx = (i == 0) ? n_in - 1 : i - 1;
    const clip_vertex_t *cur = &in[i];
    const clip_vertex_t *prev = &in[prev_idx];
    // signed distance to far plane: d = w - z (inside when d >= 0)
    fp16_t d_cur  = BORG_FP16_SUB(cur->w, cur->z);
    fp16_t d_prev = BORG_FP16_SUB(prev->w, prev->z);
    int cur_inside  = fp16_ge_zero(d_cur);
    int prev_inside = fp16_ge_zero(d_prev);
    if (cur_inside != prev_inside) {
      // t = d_prev / (d_prev - d_cur)
      fp16_t denom = BORG_FP16_SUB(d_prev, d_cur);
      fp16_t t = borg_fp16_mul(d_prev, borg_fp16_rcp(denom));
      out[n_out++] = clip_lerp(prev, cur, t);
    }
    if (cur_inside)
      out[n_out++] = *cur;
  }
  return n_out;
}

// Rasterize a single triangle from 3 clip vertices (post-clipping).
// Performs perspective division, screen-space translation, triangle setup,
// and the rasterization loop.
static void rasterize_clipped_triangle(const clip_vertex_t *cv,
                                       const texture_t *t, int frame) {

  // Perspective division
  fp16_t ndc[3][3];  // [vertex][x,y,z]
  for (int v = 0; v < 3; v++) {
    fp16_t w = (&cv[v])->w;
    fp16_t inv_w = borg_fp16_rcp(w);
    ndc[v][0] = borg_fp16_mul((&cv[v])->x, inv_w);
    ndc[v][1] = borg_fp16_mul((&cv[v])->y, inv_w);
    ndc[v][2] = borg_fp16_mul((&cv[v])->z, inv_w);
  }

  // Screen-space translation: NDC → pixel coordinates
  uv16_t spos[3];
  for (int v = 0; v < 3; v++) {
    spos[v] = (uv16_t){
      borg_fp16_fmadd(ndc[v][0], fp16_half_width, fp16_half_width),
      borg_fp16_fmadd(ndc[v][1], fp16_half_width, fp16_half_width)
    };
  }

  // Triangle setup: area and back-face culling
  fp16_t dx10 = BORG_FP16_SUB(spos[1].u, spos[0].u);
  fp16_t dy20 = BORG_FP16_SUB(spos[2].v, spos[0].v);
  fp16_t dx20 = BORG_FP16_SUB(spos[2].u, spos[0].u);
  fp16_t dy10 = BORG_FP16_SUB(spos[1].v, spos[0].v);
  fp16_t area = BORG_FP16_SUB(borg_fp16_mul(dx10, dy20),
                               borg_fp16_mul(dx20, dy10));
  if (fp16_ge_zero(area)) return;  // degenerate or back-facing
  fp16_t inv_area = borg_fp16_rcp(area);

  // Edge vectors
  uv16_t edges[3];
  compute_edge_vectors(spos, edges);

  // Build per-vertex data arrays for rasterizer
  rgb16_t colors[3] = {
    { cv[0].r, cv[0].g, cv[0].b },
    { cv[1].r, cv[1].g, cv[1].b },
    { cv[2].r, cv[2].g, cv[2].b }
  };
  fp16x3_t z_vals = { ndc[0][2], ndc[1][2], ndc[2][2] };
  const uv16_t *uvs = 0;
  uv16_t uv_vals[3];
  if (t->psram_offset >= 0) {
    uv_vals[0] = (uv16_t){ cv[0].u, cv[0].v };
    uv_vals[1] = (uv16_t){ cv[1].u, cv[1].v };
    uv_vals[2] = (uv16_t){ cv[2].u, cv[2].v };
    uvs = uv_vals;
  }

  // Rasterize + fragment shade in 4x4 blocks
  const int BLOCK_SIZE = 4;
  for (int by = 0; by < BORG_FB_HEIGHT; by += BLOCK_SIZE) {
    for (int bx = 0; bx < BORG_FB_WIDTH; bx += BLOCK_SIZE) {
      for (int py = by; py < by + BLOCK_SIZE && py < BORG_FB_HEIGHT; py++) {
        for (int px = bx; px < bx + BLOCK_SIZE && px < BORG_FB_WIDTH; px++) {
          uv16_t pc = { pc_lut[px], pc_lut[py] };
          uv16_t deltas[3];
          compute_pixel_deltas(pc, spos, deltas);
          rgb16_t color = {0, 0, 0};
          fp16_t z = 0;
          uv16_t uv_interp = {0, 0};
          int visible = borg_bary_rgb(&rast_shader, &frag_shader,
                         edges, deltas,
                         inv_area, colors, z_vals, uvs,
                         &color, &z, &uv_interp);
          if (visible)
            shade_and_write_pixel(frame, px, py, color, z, uv_interp, t);
        }
      }
    }
  }
}

void borg_cmd_draw(const borg_draw_data_t *d, const borg_vertex_t vertices[3], int frame) {
  unsigned int t_start = get_cycles();
  // Clear stale DONE marker for this frame
  PSRAM_OUT(frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE) = 0;

  // Build vertex attribute array from vertex positions
  fp16_t attrs[NUM_VERTICES * 3];
  for (int v = 0; v < NUM_VERTICES; v++) {
    attrs[v * 3 + 0] = vertices[v].pos[0];
    attrs[v * 3 + 1] = vertices[v].pos[1];
    attrs[v * 3 + 2] = vertices[v].pos[2];
  }

  // Vertex shader
  fp16_t vout[NUM_VERTICES * SPIRB_MAX_REGS];
  run_vertex_shader(d->uniforms, attrs, vout);

  int stride = vert_shader.num_outputs;

  // --- Step 6: Triangle Clipping ---
  // Build clip vertices from vertex shader output + original vertex attributes.
  clip_vertex_t clip_in[3];
  for (int v = 0; v < 3; v++) {
    clip_in[v].x = vout[v * stride + 0];
    clip_in[v].y = vout[v * stride + 1];
    clip_in[v].z = (stride >= 3) ? vout[v * stride + 2] : FP16_ZERO;
    clip_in[v].w = (stride >= 4) ? vout[v * stride + 3] : FP16_ONE;
    clip_in[v].r = vertices[v].color[0];
    clip_in[v].g = vertices[v].color[1];
    clip_in[v].b = vertices[v].color[2];
    clip_in[v].u = vertices[v].uv[0];
    clip_in[v].v = vertices[v].uv[1];
  }

  // Clip against near plane (z >= 0), then far plane (z <= w).
  clip_vertex_t clip_a[MAX_CLIP_VERTS + 1];
  clip_vertex_t clip_b[MAX_CLIP_VERTS + 2];
  int n_clip = clip_near(clip_in, 3, clip_a);
  if (n_clip < 3) goto done;
  n_clip = clip_far(clip_a, n_clip, clip_b);
  if (n_clip < 3) goto done;

  // Fan-triangulate the clipped polygon and rasterize each triangle.
  for (int i = 1; i < n_clip - 1; i++) {
    clip_vertex_t tri[3] = { clip_b[0], clip_b[i], clip_b[i + 1] };
    rasterize_clipped_triangle(tri, &tex, frame);
  }

done:  t_draw_cycles += get_cycles() - t_start;
}

void borg_present(int frame) {
  // Wait for the GPU to finish the last draw command before finalizing the frame!
  unsigned int t_wait = get_cycles();
  while (!(BORG_STATUS & BORG_STS_IDLE))
    ;
  t_draw_cycles += get_cycles() - t_wait;

  int base = frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE;
  PSRAM_OUT(base)     = DONE_MARKER;
  PSRAM_OUT(base + 1) = t_init_cycles & 0xFFFF;
  PSRAM_OUT(base + 2) = (t_init_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 3) = t_clear_cycles & 0xFFFF;
  PSRAM_OUT(base + 4) = (t_clear_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 5) = t_draw_cycles & 0xFFFF;
  PSRAM_OUT(base + 6) = (t_draw_cycles >> 16) & 0xFFFF;
}
