// SPDX-FileCopyrightText: © 2025-2026 Andreas Wendleder
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef BORG_MATH_H
#define BORG_MATH_H

#include <stdint.h>

// Documentary typedef (matches borg_fpu.h; guarded for order-independence)
#ifndef FP16_T_DEFINED
#define FP16_T_DEFINED
typedef uint16_t fp16_t;
#endif

/**
 * FP16 sin/cos using a 64-entry lookup table.
 * Angle is in FP16 radians [0, 2π).
 * Accuracy: matches FP16 precision (~3.3 digits).
 */

// Negate FP16 value (XOR sign bit)
static inline fp16_t fp16_neg(fp16_t x) {
    return x ^ 0x8000;
}

// Convert FP16 to a signed fixed-point Q16 (for add/sub)
static inline int32_t fp16_to_fixed(fp16_t f) {
    uint16_t sign = (f >> 15) & 1;
    int16_t  exp  = ((f >> 10) & 0x1F) - 15;
    uint32_t mant = (f & 0x3FF) | 0x400;  // implicit 1.mantissa
    if ((f & 0x7FFF) == 0) return 0;
    // Shift mantissa to Q16: mant is Q10, so shift by (exp + 6)
    int32_t val;
    int shift = exp + 6;
    if (shift >= 0) val = mant << shift;
    else            val = mant >> (-shift);
    return sign ? -val : val;
}

// Convert signed fixed-point Q16 back to FP16
static inline fp16_t fixed_to_fp16(int32_t v) {
    if (v == 0) return 0;
    uint16_t sign = 0;
    uint32_t uv;
    if (v < 0) { 
        sign = 0x8000; 
        uv = (uint32_t)(-v); 
    } else {
        uv = (uint32_t)v;
    }
    
    // Manual CLZ (Count Leading Zeros) for 32-bit
    uint32_t x = uv;
    int n = 32;
    uint32_t y;
    
    y = x >> 16; if (y != 0) { n -= 16; x = y; }
    y = x >>  8; if (y != 0) { n -=  8; x = y; }
    y = x >>  4; if (y != 0) { n -=  4; x = y; }
    y = x >>  2; if (y != 0) { n -=  2; x = y; }
    y = x >>  1; if (y != 0) { n -=  2; } else { n -= x; }
    
    int top = 31 - n;
    int16_t exp = top - 1;
    if (exp < 1) return sign; // underflow to 0
    if (exp > 30) return sign | 0x7C00; // overflow to infinity
    
    int shift = top - 10;
    uint16_t mant;
    if (shift >= 0) mant = (uv >> shift) & 0x3FF;
    else            mant = (uv << (-shift)) & 0x3FF;
    return sign | ((uint16_t)exp << 10) | mant;
}

// FP16 subtraction: a - b
static inline fp16_t fp16_sub(fp16_t a, fp16_t b) {
    return fixed_to_fp16(fp16_to_fixed(a) - fp16_to_fixed(b));
}

// FP16 addition: a + b
static inline fp16_t fp16_add(fp16_t a, fp16_t b) {
    return fixed_to_fp16(fp16_to_fixed(a) + fp16_to_fixed(b));
}

// FP16 reciprocal: 1.0 / x (software, no fdiv needed)
static inline fp16_t fp16_recip(fp16_t x) {
    int32_t fx = fp16_to_fixed(x);
    if (fx == 0) return 0x7C00; // +inf
    // We want (1.0 in Q16) / fx = 65536 / fx
    // But fp16_to_fixed returns value*65536 for Q16,
    // so fx already is value*65536... not quite.
    // fp16_to_fixed shifts mantissa by (exp+6), giving value*1024 roughly.
    // Let's just do: result = 1.0/value via scaling.
    // fp16_to_fixed(0x3C00) = (1024+0) << (0+6) = 1024*64 = 65536
    // So fp16_to_fixed gives value * 65536 (Q16 format).
    // recip = 1.0 / value. In Q16: recip_q16 = 65536 / value = 65536 * 65536 / fx
    // But that overflows 32-bit. Use 64-bit or reduce precision.
    int32_t sign = 1;
    if (fx < 0) { sign = -1; fx = -fx; }
    // result_q16 = (1<<32) / fx, but that needs 64-bit
    // Alternatively: result = (1<<30) / fx, then shift right by 14 to get Q16
    // (1<<30)/fx gives result in Q(30-16)=Q14, we need Q16, so shift left 2
    int32_t result = ((int32_t)1 << 30) / fx;
    result <<= 2; // now Q16
    if (sign < 0) result = -result;
    return fixed_to_fp16(result);
}

// FP16 constants
#define FP16_ZERO     0x0000
#define FP16_ONE      0x3C00
#define FP16_PI       0x4248  // 3.14062
#define FP16_HALF_PI  0x3E48  // 1.57031
#define FP16_TWO_PI   0x4648  // 6.28125

// sin LUT: 65 entries for sin(i * π/128), i = 0..64
// Generated by numpy: int(np.float16(math.sin(i*pi/128)).view(np.uint16))
static const uint16_t sin_lut[65] = {
    0x0000, 0x2648, 0x2A48, 0x2CB5, 0x2E46, 0x2FD6, 0x30B2, 0x3179,
    0x323E, 0x3303, 0x33C6, 0x3444, 0x34A5, 0x3505, 0x3564, 0x35C2,
    0x361F, 0x367C, 0x36D7, 0x3732, 0x378B, 0x37E3, 0x381D, 0x3848,
    0x3872, 0x389B, 0x38C4, 0x38EC, 0x3913, 0x393A, 0x395F, 0x3984,
    0x39A8, 0x39CB, 0x39ED, 0x3A0F, 0x3A2F, 0x3A4F, 0x3A6D, 0x3A8A,
    0x3AA7, 0x3AC2, 0x3ADD, 0x3AF6, 0x3B0E, 0x3B25, 0x3B3B, 0x3B50,
    0x3B64, 0x3B77, 0x3B88, 0x3B99, 0x3BA8, 0x3BB6, 0x3BC3, 0x3BCE,
    0x3BD9, 0x3BE2, 0x3BEA, 0x3BF1, 0x3BF6, 0x3BFA, 0x3BFE, 0x3BFF,
    0x3C00,
};

/** Compute FP16 sin(angle) where angle is FP16 radians. */
fp16_t fp16_sin(fp16_t angle_fp16);

/** Compute FP16 cos(angle) = sin(angle + π/2). */
fp16_t fp16_cos(fp16_t angle_fp16);

#endif // BORG_MATH_H
