// SPDX-FileCopyrightText: © 2025-2026 Andreas Wendleder
// SPDX-License-Identifier: GPL-3.0-or-later

// Borg GPU driver — pipeline orchestration, hardware init, draw commands.

#include "borg_driver.h"
#include "borg_fpu.h"
#include "borg_raster.h"
#include "borg_math.h"
#include "borg_spirb.h"

// @doc:mmio-map
#include "borg_mmio.h"  // Auto-generated by MmioMap.scala
// @doc:end

#define FP16_SIXTEEN 0x4C00

static inline void fb_write_pixel(int base, rgb16_t c) {
  PSRAM_OUT(base + 0) = c.r;
  PSRAM_OUT(base + 1) = c.g;
  PSRAM_OUT(base + 2) = c.b;
}

static inline rgb16_t fb_read_texel(int base) {
  return (rgb16_t){ PSRAM_IN(base + 0), PSRAM_IN(base + 1), PSRAM_IN(base + 2) };
}

typedef struct { int w, h; } dim2_t;

typedef struct {
  int psram_offset;        // -1 = no texture
  dim2_t size;             // integer dimensions
  uint16_t w_fp16, h_fp16; // FP16 dimensions for Borg FPU
} texture_t;

// Runtime framebuffer dimensions and derived values
int borg_fb_width;
int borg_fb_height;
static fp16_t fp16_half_width;
static fp16_t pc_lut[BORG_MAX_FB_DIM];

#define NUM_VERTICES 3

// Global timing vars
unsigned int t_init_cycles = 0;
unsigned int t_clear_cycles = 0;
unsigned int t_draw_cycles = 0;

// --- Texture state ---
static texture_t tex = { .psram_offset = -1 };

// --- UART ---
void putc_uart(int c) {
  while (UART_STATUS & 1)
    ;
  UART_TX = c;
}
static void puts_uart(const char *s) {
  while (*s)
    putc_uart(*s++);
}

// --- Timing and debug printing ---
static inline unsigned int get_cycles(void) {
  unsigned int cycles;
  __asm__ volatile ("csrr %0, cycle" : "=r" (cycles));
  return cycles;
}



// --- Shader globals ---
static spirb_shader_t vert_shader;
static spirb_shader_t rast_shader;
static spirb_shader_t frag_shader;

// --- Vertex shader ---
static void run_vertex_shader(const fp16_t *uniforms,
                               const fp16_t *attrs,
                               fp16_t *outputs) {
  const spirb_shader_t *s = &vert_shader;
  borg_load_spirb_shader(s);

  for (int i = 0; i < s->num_uniforms; i++)
    BORG_REG(s->uniform_regs[i]) = uniforms[i];

  for (int v = 0; v < NUM_VERTICES; v++) {
    BORG_CONTROL = BORG_CTL_RESET;
    for (int i = 0; i < s->num_uniforms; i++)
      BORG_REG(s->uniform_regs[i]) = uniforms[i];
    for (int i = 0; i < s->num_attributes; i++)
      BORG_REG(s->attribute_regs[i]) = attrs[v * s->num_attributes + i];
    for (int i = 0; i < s->num_consts; i++)
      BORG_REG(s->const_regs[i]) = s->const_vals[i];
    borg_run();
    for (int i = 0; i < s->num_outputs; i++)
      outputs[v * s->num_outputs + i] = BORG_REG(s->output_regs[i]) & 0xFFFF;
  }
  puts_uart("D\r\n");
}

// --- Public API ---

static inline uint32_t morton_interleave(uint32_t x) {
  x = (x | (x << 8)) & 0x00FF00FF;
  x = (x | (x << 4)) & 0x0F0F0F0F;
  x = (x | (x << 2)) & 0x33333333;
  x = (x | (x << 1)) & 0x55555555;
  return x;
}

static inline uint32_t morton_encode(uint32_t x, uint32_t y) {
  return morton_interleave(x) | (morton_interleave(y) << 1);
}

// Small delay loop necessary to wait for system/Pico to be fully ready
void borg_init(const uint8_t *vert_blob, unsigned int vert_len,
               const uint8_t *rast_blob, unsigned int rast_len,
               const uint8_t *frag_blob, unsigned int frag_len) {
  STARTUP_DELAY();
  UART_BAUD = UART_BAUD_DEFAULT;
  puts_uart("Borg pipeline\r\n");
  unsigned int t_init = get_cycles();

  // Read framebuffer dimensions from PSRAM (written by host)
  borg_fb_width  = PSRAM_IN(0) & 0xFFFF;
  borg_fb_height = PSRAM_IN(1) & 0xFFFF;
  if (borg_fb_width == 0 || borg_fb_width > BORG_MAX_FB_DIM) borg_fb_width = 16;
  if (borg_fb_height == 0 || borg_fb_height > BORG_MAX_FB_DIM) borg_fb_height = 16;

  // Compute FP16 half-width for NDC→screen transform
  // half_width = width / 2 (integer), then convert to FP16
  int hw = borg_fb_width / 2;
  // Simple integer-to-FP16 for powers of 2 (8, 16, 32)
  int exp = 0;
  int tmp = hw;
  while (tmp > 1) { tmp >>= 1; exp++; }
  fp16_half_width = ((exp + 15) << 10);  // power-of-2, mantissa=0

  // Compute pixel center LUT: 0.5, 1.5, ..., (width-0.5)
  fp16_t val = FP16_HALF;  // 0.5
  for (int i = 0; i < borg_fb_width; i++) {
    pc_lut[i] = val;
    val = borg_fp16_add(val, FP16_ONE);
  }

  spirb_parse(vert_blob, &vert_shader);
  spirb_parse(rast_blob, &rast_shader);
  spirb_parse(frag_blob, &frag_shader);
  t_init_cycles = get_cycles() - t_init;
}

void borg_set_angle(borg_draw_data_t *d, fp16_t angle_fp16) {
  // Compute vertex shader uniforms from angle
  // The vertex shader expects: uniform[0]=sin, uniform[1]=cos, uniform[2]=-sin
  d->uniforms[0] = fp16_sin(angle_fp16);
  d->uniforms[1] = fp16_cos(angle_fp16);
  d->uniforms[2] = fp16_neg(d->uniforms[0]);
}

#define FRAME_FB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT * 3)  // RGB words
#define FRAME_ZB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT)        // Z-buffer words
#define FRAME_STRIDE  (FRAME_FB_SIZE + FRAME_ZB_SIZE + 1)     // FB + ZB + DONE marker

void borg_clear_zbuffer(int frame) {
  unsigned int t_start = get_cycles();
  int fb_offset = frame * FRAME_STRIDE;
  int zb_offset = fb_offset + FRAME_FB_SIZE;
  // Clear RGB framebuffer to black
  for (int i = 0; i < FRAME_FB_SIZE; i++)
    PSRAM_OUT(fb_offset + i) = 0;
  // Clear z-buffer to max depth
  for (int i = 0; i < FRAME_ZB_SIZE; i++)
    PSRAM_OUT(zb_offset + i) = FP16_MAX_DEPTH;
  t_clear_cycles = get_cycles() - t_start;
}

void borg_set_texture(int psram_offset, int width, int height) {
  tex = (texture_t){
    .psram_offset = psram_offset,
    .size = { width, height },
    .w_fp16 = uint_to_fp16(width), .h_fp16 = uint_to_fp16(height)
  };
}

void borg_clear_texture(void) {
  tex.psram_offset = -1;
}

static void shade_and_write_pixel(int frame, int px, int py,
                                  rgb16_t color, fp16_t z, uv16_t uv_interp,
                                  const texture_t *t) {
  // Depth test: read current z, compare (closer = smaller)
  int zb_idx = frame * FRAME_STRIDE + FRAME_FB_SIZE + (py * BORG_FB_WIDTH + px);
  fp16_t old_z = PSRAM_OUT(zb_idx);
  if (z >= old_z) return;
  PSRAM_OUT(zb_idx) = z;

  // Texture sampling: replace vertex colors with texel
  if (t->psram_offset >= 0) {
    texcoord_t tc = uv_to_texcoord(uv_interp, t->w_fp16, t->h_fp16);
    if (tc.x >= t->size.w)  tc.x = t->size.w - 1;
    if (tc.y >= t->size.h) tc.y = t->size.h - 1;
    int morton_idx = morton_encode(tc.x, tc.y);
    int texel = t->psram_offset + morton_idx * 3;
    color = fb_read_texel(texel);
  }

  int base = frame * FRAME_STRIDE + (py * BORG_FB_WIDTH + px) * 3;
  fb_write_pixel(base, color);
}

void borg_cmd_draw(const borg_draw_data_t *d, const borg_vertex_t vertices[3], int frame) {
  unsigned int t_start = get_cycles();
  // Clear stale DONE marker for this frame
  PSRAM_OUT(frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE) = 0;
  // Build colors array from vertex data
  fp16_t colors[3][3];
  for (int v = 0; v < 3; v++)
    for (int c = 0; c < 3; c++)
      colors[v][c] = vertices[v].color[c];
  // Build vertex attribute array from vertex positions
  fp16_t attrs[NUM_VERTICES * 2];
  for (int v = 0; v < NUM_VERTICES; v++) {
    attrs[v * 2 + 0] = vertices[v].pos[0];
    attrs[v * 2 + 1] = vertices[v].pos[1];
  }

  // Vertex shader
  fp16_t vout[NUM_VERTICES * SPIRB_MAX_REGS];
  run_vertex_shader(d->uniforms, attrs, vout);

  // Screen-space translation
  uv16_t spos[3];
  screen_space_translate(&vert_shader, vout, spos, fp16_half_width);

  // Triangle setup: compute inv_area from screen-space positions
  // area = (sx1-sx0)*(sy2-sy0) - (sx2-sx0)*(sy1-sy0) (2D cross product)
  fp16_t dx10 = BORG_FP16_SUB(spos[1].u, spos[0].u);
  fp16_t dy20 = BORG_FP16_SUB(spos[2].v, spos[0].v);
  fp16_t dx20 = BORG_FP16_SUB(spos[2].u, spos[0].u);
  fp16_t dy10 = BORG_FP16_SUB(spos[1].v, spos[0].v);
  fp16_t area = BORG_FP16_SUB(borg_fp16_mul(dx10, dy20),
                                 borg_fp16_mul(dx20, dy10));
  fp16_t inv_area = borg_fp16_rcp(area);

  // Edge vectors
  uv16_t edges[3];
  compute_edge_vectors(spos, edges);
  puts_uart("F\r\n");

  // Rasterize + fragment shade in 4x4 Blocks
  const int BLOCK_SIZE = 4;
  for (int by = 0; by < BORG_FB_HEIGHT; by += BLOCK_SIZE) {
    for (int bx = 0; bx < BORG_FB_WIDTH; bx += BLOCK_SIZE) {
      for (int py = by; py < by + BLOCK_SIZE && py < BORG_FB_HEIGHT; py++) {
        for (int px = bx; px < bx + BLOCK_SIZE && px < BORG_FB_WIDTH; px++) {
          uv16_t pc = { pc_lut[px], pc_lut[py] };
          uv16_t deltas[3];
          compute_pixel_deltas(pc, spos, deltas);
          rgb16_t color = {0, 0, 0};
          fp16_t z = 0;
          uv16_t uv_interp = {0, 0};
          fp16_t z_vals[3] = { vertices[0].pos[2], vertices[1].pos[2], vertices[2].pos[2] };
          const uv16_t *uvs = 0;
          uv16_t uv_vals[3];
          if (tex.psram_offset >= 0) {
            for (int i = 0; i < 3; i++) {
              uv_vals[i] = (uv16_t){ vertices[i].uv[0], vertices[i].uv[1] };
            }
            uvs = uv_vals;
          }
          int visible = borg_bary_rgb(&rast_shader, &frag_shader,
                         edges, deltas,
                         inv_area, colors, z_vals, uvs,
                         &color, &z, &uv_interp);
          if (visible)
            shade_and_write_pixel(frame, px, py, color, z, uv_interp, &tex);
        }
      }
    }
  }
  t_draw_cycles += get_cycles() - t_start;
}

void borg_present(int frame) {
  // Wait for the GPU to finish the last draw command before finalizing the frame!
  unsigned int t_wait = get_cycles();
  while (!(BORG_STATUS & BORG_STS_IDLE))
    ;
  t_draw_cycles += get_cycles() - t_wait;

  int base = frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE;
  PSRAM_OUT(base)     = DONE_MARKER;
  PSRAM_OUT(base + 1) = t_init_cycles & 0xFFFF;
  PSRAM_OUT(base + 2) = (t_init_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 3) = t_clear_cycles & 0xFFFF;
  PSRAM_OUT(base + 4) = (t_clear_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 5) = t_draw_cycles & 0xFFFF;
  PSRAM_OUT(base + 6) = (t_draw_cycles >> 16) & 0xFFFF;
}
