// Generated by CIRCT firtool-1.140.0
`ifndef layers_Borg_Verification_Assume	// /home/gonsolo/work/Borg/borg/src/Borg.scala:30:7
  `define layers_Borg_Verification_Assume
  `include "layers-Borg-Verification.sv"	// /home/gonsolo/work/Borg/borg/src/Borg.scala:30:7
`endif // not def layers_Borg_Verification_Assume
