#!/usr/bin/env python3
"""Generate Chisel register blocks, C headers, and Python constants from RDL."""

import os
import sys
import systemrdl
from systemrdl.node import AddrmapNode, RegNode
from peakrdl_chisel import ChiselExporter
from peakrdl_cheader.exporter import CHeaderExporter

rdl_dir = os.path.dirname(os.path.abspath(__file__))

scala_out_dir = sys.argv[1] if len(sys.argv) > 1 else "hardware/borg/src/generated/"
c_out_dir = sys.argv[2] if len(sys.argv) > 2 else "out/hardware/borg/rdl/"

os.makedirs(scala_out_dir, exist_ok=True)
os.makedirs(c_out_dir, exist_ok=True)

chisel = ChiselExporter()
cheader = CHeaderExporter()

# Each peripheral is compiled independently so each gets its own
# uniquely-named Chisel companion object (e.g. BorgGpuRegs, GpioMapRegs).
peripherals = [
    {"name": "borg",  "rdl": "borg.rdl"},
    {"name": "gpio",  "rdl": "gpio.rdl"},
    {"name": "uart",  "rdl": "uart.rdl"},
    {"name": "psram", "rdl": "psram.rdl"},
]

for p in peripherals:
    rdlc = systemrdl.RDLCompiler()
    rdlc.compile_file(os.path.join(rdl_dir, p["rdl"]))
    root = rdlc.elaborate()

    for child in root.children():
        if isinstance(child, AddrmapNode):
            # Chisel register block
            chisel.export(child, scala_out_dir, package_name="borg")
            print(f"Generated Chisel: {p['name']}")

            # C header
            cheader_file = os.path.join(c_out_dir, f"{p['name']}_regs.h")
            cheader.export(child, cheader_file)
            print(f"Generated C header: {cheader_file}")

# Also compile the full SoC for the combined C header (has base addresses)
rdlc_soc = systemrdl.RDLCompiler()
for f in [os.path.join(rdl_dir, n) for n in ["gpio.rdl", "uart.rdl", "psram.rdl", "borg.rdl", "soc.rdl"]]:
    rdlc_soc.compile_file(f)
root_soc = rdlc_soc.elaborate()
for child in root_soc.children():
    if isinstance(child, AddrmapNode):
        soc_header = os.path.join(c_out_dir, "soc_regs.h")
        cheader.export(child, soc_header)
        print(f"Generated SoC C header: {soc_header}")


# ============================================================================
# Python constants generation
# ============================================================================

def collect_rdl_constants(soc_root):
    """Walk the SoC addrmap and extract base addresses + register offsets."""
    consts = {}
    for child in soc_root.children():
        if not isinstance(child, AddrmapNode):
            continue
        # This is the top SoC addrmap
        for peri in child.children():
            if isinstance(peri, AddrmapNode):
                name = peri.inst_name.upper()
                consts[f"{name}_BASE"] = peri.absolute_address
                # Collect register offsets within this peripheral
                for reg in peri.children():
                    if isinstance(reg, RegNode):
                        rname = reg.inst_name.upper()
                        offset = reg.address_offset if not reg.is_array else reg.raw_address_offset
                        consts[f"{name}_{rname}_OFFSET"] = offset
    return consts


def emit_python(path, rdl_consts):
    """Generate a Python constants file from RDL + static bus-decode constants."""
    with open(path, "w") as f:
        f.write("# Auto-generated by hardware/rdl/generate.py — do not edit manually\n")
        f.write("# Source of truth: hardware/rdl/*.rdl\n")
        f.write("\n")

        # --- RDL-derived constants (base addresses, register offsets) ---
        f.write("# --- Peripheral base addresses (from soc.rdl) ---\n")
        bases = {k: v for k, v in sorted(rdl_consts.items()) if k.endswith("_BASE")}
        for k, v in bases.items():
            f.write(f"{k} = 0x{v:08X}\n")
        f.write("\n")

        f.write("# --- Borg GPU register offsets (from borg.rdl) ---\n")
        borg_regs = {k: v for k, v in sorted(rdl_consts.items()) if k.startswith("BORG_") and k.endswith("_OFFSET")}
        for k, v in borg_regs.items():
            # Strip BORG_ prefix for cleaner names matching legacy convention
            short = k.replace("BORG_", "BORG_")  # keep as-is for clarity
            f.write(f"{k} = 0x{v:03X}\n")
        f.write("\n")

        f.write("# --- GPIO register offsets (from gpio.rdl) ---\n")
        gpio_regs = {k: v for k, v in sorted(rdl_consts.items()) if k.startswith("GPIO_") and k.endswith("_OFFSET")}
        for k, v in gpio_regs.items():
            f.write(f"{k} = {v}\n")
        f.write("\n")

        f.write("# --- UART register offsets (from uart.rdl) ---\n")
        uart_regs = {k: v for k, v in sorted(rdl_consts.items()) if k.startswith("UART_") and k.endswith("_OFFSET")}
        for k, v in uart_regs.items():
            f.write(f"{k} = {v}\n")
        f.write("\n")

        # --- Static constants (bus decode, system, ISA) ---
        # These are TinyQV bus-decoder mechanics that cannot come from RDL.
        f.write("# --- TinyQV bus decoder constants ---\n")
        f.write("USER_BASE = 0x08000000\n")
        f.write("BUS_IDLE = 3\n")
        f.write("USER_PERI_GPIO = 1\n")
        f.write("USER_PERI_UART = 2\n")
        f.write("USER_PERI_BORG = 3\n")
        f.write("USER_PERI_STRIDE = 512\n")
        f.write("USER_PERI_SEL_HI = 10\n")
        f.write("USER_PERI_SEL_LO = 9\n")
        f.write("USER_SUB_ADDR_HI = 8\n")
        f.write("USER_SUB_ADDR_LO = 0\n")
        f.write("\n")

        f.write("# --- SoC peripheral indices (addr[5:2]) ---\n")
        f.write("PERI_NONE = 0x0\n")
        f.write("PERI_ID = 0x2\n")
        f.write("PERI_GPIO_OUT_SEL = 0x3\n")
        f.write("PERI_DEBUG_UART = 0x6\n")
        f.write("PERI_DEBUG_UART_STATUS = 0x7\n")
        f.write("PERI_DEBUG_UART_BAUD = 0x8\n")
        f.write("PERI_TIME_LIMIT = 0xB\n")
        f.write("PERI_DEBUG = 0xC\n")
        f.write("PERI_USER = 0xF\n")
        f.write("SOC_PERI_ID_OFFSET = PERI_ID * 4\n")
        f.write("SOC_PERI_GPIO_OUT_SEL_OFFSET = PERI_GPIO_OUT_SEL * 4\n")
        f.write("SOC_PERI_DEBUG_UART_OFFSET = PERI_DEBUG_UART * 4\n")
        f.write("SOC_PERI_TIME_LIMIT_OFFSET = PERI_TIME_LIMIT * 4\n")
        f.write("\n")

        f.write("# --- GPIO address decode (bit positions, not RDL register offsets) ---\n")
        f.write("GPIO_FUNC_SEL_BIT = 5\n")
        f.write("GPIO_FUNC_SEL_IDX_HI = 4\n")
        f.write("GPIO_FUNC_SEL_IDX_LO = 2\n")
        f.write("\n")

        f.write("# --- System constants ---\n")
        f.write("CLOCK_MHZ = 4\n")
        f.write("FPGA_CLOCK_HZ = CLOCK_MHZ * 1000000\n")
        f.write("UART_BAUD_DEFAULT = FPGA_CLOCK_HZ // 115200\n")
        f.write("DONE_MARKER = 0x0000DEAD\n")
        f.write("STARTUP_DELAY_CYCLES = 10000\n")
        f.write("PSRAM_SPI_BASE = 0x00001000\n")
        f.write("PSRAM_IO_SPI_ADDR = PSRAM_SPI_BASE\n")
        f.write("PSRAM_OUT_OFFSET = 128\n")
        f.write("TEX_PSRAM_OFFSET = 4200\n")
        f.write("\n")
        
        f.write("# --- SPIR-B Format Constants ---\n")
        f.write("SPIRB_INSTR_BYTES = 4\n")
        f.write("\n")

        f.write("# --- Borg instruction encoding (32-bit RISC-V R-type / R4-type) ---\n")
        f.write("def encode_rv32_fadd(rs1=0, rs2=1, rd=2, funct3=0):\n")
        f.write("    return (0x00000000 | (funct3 << 12) | (rs2 << 20) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_fmul(rs1=0, rs2=1, rd=2, funct3=0):\n")
        f.write("    return (0x08000000 | (funct3 << 12) | (rs2 << 20) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_fmadd(rs1=0, rs2=1, rs3=3, rd=2, funct3=0):\n")
        f.write("    return (0x00000004 | (funct3 << 12) | (rs3 << 27) | (rs2 << 20) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_fneg(rs1=0, rd=1, funct3=0):\n")
        f.write("    return (0x0C000000 | (funct3 << 12) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_fstep(rs1=0, rd=1, funct3=0):\n")
        f.write("    return (0x10000000 | (funct3 << 12) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_frcp(rs1=0, rd=1, funct3=0):\n")
        f.write("    return (0x14000000 | (funct3 << 12) | (rs1 << 15) | (rd << 7))\n")
        f.write("def encode_rv32_halt(): return 0x00000000\n")

    print(f"Generated Python: {path}")


# Generate Python constants (single canonical copy — Makefile copies to consumers)
rdl_consts = collect_rdl_constants(root_soc)
emit_python(os.path.join(c_out_dir, "borg_mmio.py"), rdl_consts)

print(f"\nChisel output: {scala_out_dir}")
print(f"C header output: {c_out_dir}")
