# Auto-generated by MmioMap.scala — do not edit manually

# --- System clock ---
CLOCK_MHZ = 4

# --- Shared PSRAM layout ---
TEX_PSRAM_OFFSET = 4200
DONE_MARKER = 0xDEAD

# --- SPIR-B binary format ---
SPIRB_INSTR_BYTES = 4

# --- Borg instruction encoding (32-bit RISC-V R-type / R4-type) ---
def encode_rv32_fadd(rs1=0, rs2=1, rd=2):
    return (0x00000000 | (rs2 << 20) | (rs1 << 15) | (rd << 7))
def encode_rv32_fmul(rs1=0, rs2=1, rd=2):
    return (0x08000000 | (rs2 << 20) | (rs1 << 15) | (rd << 7))
def encode_rv32_fmadd(rs1=0, rs2=1, rs3=3, rd=2):
    return (0x00000004 | (rs3 << 27) | (rs2 << 20) | (rs1 << 15) | (rd << 7))
def encode_rv32_fneg(rs1=0, rd=1):
    return (0x0C000000 | (rs1 << 15) | (rd << 7))
def encode_rv32_fstep(rs1=0, rd=1):
    return (0x10000000 | (rs1 << 15) | (rd << 7))
def encode_rv32_frcp(rs1=0, rd=1):
    return (0x14000000 | (rs1 << 15) | (rd << 7))
def encode_rv32_halt(): return 0x00000000

# --- PSRAM addresses (QSPI/SPI space) ---
PSRAM_IO_SPI_ADDR = 0x001000
PSRAM_OUT_OFFSET = 128

# --- System clock additions ---
FPGA_CLOCK_HZ = 4000000  # CLOCK_MHZ * 1e6

# --- User peripheral addressing (for TinyQV bus driver) ---
USER_PERIPHERAL_STRIDE = 0x100

# --- SoC peripheral offsets (tp-relative, bypass user peripheral decoding) ---
SOC_PERI_ID           = 0x08
SOC_PERI_GPIO_OUT_SEL = 0x0C
SOC_PERI_DEBUG_UART   = 0x18
SOC_PERI_TIME_LIMIT   = 0x2C

# --- User peripheral base offsets (tp-relative) ---
GPIO_BASE = 0x100
UART_BASE = 0x200
BORG_USER_BASE = 0x300

# --- GPIO sub-register offsets (relative to GPIO_BASE) ---
GPIO_OUT = 0
GPIO_IN = 4
GPIO_FUNC_SEL = GPIO_BASE + 0x20  # func_sel register space

# --- UART sub-register offsets (relative to UART_BASE) ---
UART_TX_DATA = 0
UART_STATUS = 4

# --- Borg GPU sub-register offsets ---
BORG_IMEM_OFFSET = 128
BORG_CONTROL_OFFSET = 252
