# Auto-generated by MmioMap.scala — do not edit manually

# PSRAM addresses (QSPI/SPI space)
PSRAM_IO_SPI_ADDR = 0x001000
PSRAM_OUT_OFFSET = 128

# Shared layout constants
TEX_PSRAM_OFFSET = 4200
DONE_MARKER = 0xDEAD
