# SPDX-FileCopyrightText: (c) 2025-2026 Andreas Wendleder
# SPDX-License-Identifier: GPL-3.0-or-later

# Host-side script for Borg triangle rendering on pico-ice FPGA.
# One-way test: firmware writes results to PSRAM, host reads them.
# Uses PIO-based QPI read (no exit sequence needed).

import math
import time
import struct
import rp2
import machine
from machine import Pin, SPI

import run_tinyqv

from borg_mmio import PSRAM_IO_SPI_ADDR, PSRAM_OUT_OFFSET, TEX_PSRAM_BYTE_OFFSET, DONE_MARKER, FPGA_CLOCK_HZ


# This PIO program handles high-speed timing to transfer data from the workstation into the PSRAM on the PMOD.
@rp2.asm_pio(autopush=True, push_thresh=8, in_shiftdir=rp2.PIO.SHIFT_LEFT,
             autopull=True, pull_thresh=8, out_shiftdir=rp2.PIO.SHIFT_RIGHT,
             out_init=(rp2.PIO.IN_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.IN_HIGH,
                       rp2.PIO.IN_HIGH, rp2.PIO.IN_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.OUT_HIGH),
             sideset_init=(rp2.PIO.OUT_HIGH))
def qspi_write():
    out(x, 8).side(1)
    out(y, 8).side(1)
    out(pindirs, 8).side(1)
    
    label("cmd_loop")
    out(pins, 8).side(0)
    jmp(x_dec, "cmd_loop").side(1)
    
    label("data_loop")
    out(pins, 8).side(0)
    jmp(y_dec, "data_loop").side(1)
    
    out(pins, 8).side(1)
    out(pindirs, 8).side(1)

# --- QSPI PIO pin positions (directly match pico-ice PMOD wiring) ---
# PIO byte bit → physical pin function
PIN_SD1  = 0   # QSPI data bit 1
PIN_CS   = 1   # Chip select (directly active-low via PIO)
PIN_SCK  = 2   # Clock (PIO sideset, not in data byte)
PIN_SD0  = 3   # QSPI data bit 0
PIN_RAMA = 4   # RAM A select
PIN_SD2  = 5   # QSPI data bit 2
PIN_RAMB = 6   # RAM B select
PIN_SD3  = 7   # QSPI data bit 3

# Idle state: CS=1 (deselected), RAMA=1, RAMB=1, SCK=1, all SD lines low
QSPI_IDLE = (1 << PIN_RAMB) | (1 << PIN_RAMA) | (1 << PIN_SCK) | (1 << PIN_CS)  # 0b01010110 = 0x56
QSPI_ALL_OUTPUT = 0xFF  # All 8 PIO pins set to output

# All QSPI bus pins (for bulk init/release in fpga_boot/teardown)
QSPI_PINS = [PIN_SD1, PIN_CS, PIN_SCK, PIN_SD0, PIN_RAMA, PIN_SD2, PIN_RAMB, PIN_SD3]

# PSRAM QPI commands
PSRAM_CMD_WRITE     = 0x02  # QPI Write
PSRAM_CMD_FAST_READ = 0x0B  # QPI Fast Read

# Command + 24-bit address = 8 nibbles
CMD_ADDR_NIBBLES = 8


def nibble_to_pio(n):
    """Map a 4-bit data nibble to the 8-pin PIO byte for QSPI bus."""
    return (((n >> 3) & 1) << PIN_SD3 |
            ((n >> 2) & 1) << PIN_SD2 |
            ((n >> 1) & 1) << PIN_SD1 |
            ((n >> 0) & 1) << PIN_SD0 |
            (1 << PIN_CS) |
            (1 << PIN_RAMB))


def pio_to_nibble(b):
    """Extract a 4-bit data nibble from a PIO pin byte (inverse of nibble_to_pio)."""
    return (((b >> PIN_SD3) & 1) << 3 |
            ((b >> PIN_SD2) & 1) << 2 |
            ((b >> PIN_SD1) & 1) << 1 |
            ((b >> PIN_SD0) & 1) << 0)

def send_qpi_cmd_addr(sm, cmd, addr):
    """Send QPI command byte and 24-bit address as nibbles."""
    sm.put(nibble_to_pio(0))
    sm.put(nibble_to_pio(cmd))
    for shift in range(20, -4, -4):
        sm.put(nibble_to_pio((addr >> shift) & 0xF))


# This function formats the Quad-SPI write protocol (command and address) and feeds it to the PIO hardware engine.
def qpi_write(sm, addr, data_bytes):
    # Setup the PIO state machine for a Write (0x02) in QPI mode
    num_bytes = len(data_bytes)
    
    # x = 8 cmd nibbles - 1
    sm.put(CMD_ADDR_NIBBLES - 1)
    # y = data nibbles - 1
    sm.put(num_bytes * 2 - 1)
    
    # pindirs
    sm.put(QSPI_ALL_OUTPUT) 
    
    send_qpi_cmd_addr(sm, PSRAM_CMD_WRITE, addr)
    
    for b in data_bytes:
        sm.put(nibble_to_pio((b >> 4) & 0xF))
        sm.put(nibble_to_pio(b & 0xF))
        
    sm.put(QSPI_ALL_OUTPUT)
    sm.put(QSPI_IDLE)

def qpi_write_word(sm, addr, value):
    data = struct.pack('<I', value & 0xFFFFFFFF)
    qpi_write(sm, addr, data)

# PSRAM_IO_SPI_ADDR imported from borg_mmio.py (generated by MmioMap.scala)

# This PIO program handles high-speed timing to read data from the PSRAM back to the workstation.
@rp2.asm_pio(autopush=True, push_thresh=8, in_shiftdir=rp2.PIO.SHIFT_LEFT,
             autopull=True, pull_thresh=8, out_shiftdir=rp2.PIO.SHIFT_RIGHT,
             out_init=(rp2.PIO.IN_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.IN_HIGH,
                       rp2.PIO.IN_HIGH, rp2.PIO.IN_HIGH, rp2.PIO.OUT_HIGH, rp2.PIO.OUT_HIGH),
             sideset_init=(rp2.PIO.OUT_HIGH))
def qspi_read():
    out(x, 8).side(1)
    out(y, 8).side(1)
    out(pindirs, 8).side(1)
    
    label("cmd_loop")
    out(pins, 8).side(0)
    jmp(x_dec, "cmd_loop").side(1)
    
    out(pindirs, 8).side(0)
    label("data_loop")
    in_(pins, 8).side(1)
    jmp(y_dec, "data_loop").side(0)
    
    out(pins, 8).side(1)
    out(pindirs, 8).side(1)

# This function formats the Quad-SPI read protocol (command and address) and collects data from the PIO hardware engine.
def qpi_read(sm, addr, num_bytes):
    # Setup the PIO state machine for a Fast Read (0x0B) in QPI mode
    buf = bytearray(num_bytes * 2 + 4)
    
    # x = 8 cmd nibbles - 1
    sm.put(CMD_ADDR_NIBBLES - 1)
    # y = data nibbles + dummy nibbles - 1 (2 data nibbles/byte + 4 dummy nibbles)
    sm.put(num_bytes * 2 + 4 - 1)
    
    # pindirs
    sm.put(QSPI_ALL_OUTPUT) 
    
    send_qpi_cmd_addr(sm, PSRAM_CMD_FAST_READ, addr)
    
    # pindirs for read
    sm.put(QSPI_IDLE)
    
    for i in range(num_bytes * 2 + 4):
        buf[i] = sm.get()
        
    sm.put(QSPI_ALL_OUTPUT)
    sm.put(QSPI_IDLE)
    
    # Reassemble bytes from nibbles (skip 4 dummy nibbles)
    out_buf = bytearray(num_bytes)
    for i in range(num_bytes):
        h = buf[4 + i * 2]
        l = buf[4 + i * 2 + 1]
        
        # Extract data nibble from PIO pin byte using named pin positions
        hn = pio_to_nibble(h)
        ln = pio_to_nibble(l)

        out_buf[i] = (hn << 4) | ln
        
    return out_buf


def qpi_read_word(sm, addr):
    data = qpi_read(sm, addr, 4)
    return struct.unpack('<I', data)[0]


def fpga_boot(run_seconds=1):
    """Boot the FPGA: release reset, set up QSPI pins, start clock, wait.
    Returns (clk_pwm, ice_creset_b) for teardown."""
    ice_creset_b = machine.Pin(27, machine.Pin.OUT)
    ice_done = machine.Pin(26, machine.Pin.IN)
    time.sleep_us(10)
    ice_creset_b.value(1)

    while ice_done.value() == 0:
        time.sleep(0.001)

    rst_n = Pin(12, Pin.OUT)
    clk = Pin(24, Pin.OUT)
    clk.off()
    rst_n.on()
    time.sleep(0.001)
    rst_n.off()

    clk.on()
    time.sleep(0.001)
    clk.off()
    time.sleep(0.001)

    flash_sel = Pin(PIN_CS, Pin.OUT)
    qspi_sd0  = Pin(PIN_SD0, Pin.OUT)
    qspi_sd1  = Pin(PIN_SD1, Pin.OUT)
    qspi_sd2  = Pin(PIN_SD2, Pin.OUT)
    ram_a_sel = Pin(PIN_RAMA, Pin.OUT)
    ram_b_sel = Pin(PIN_RAMB, Pin.OUT)

    flash_sel.on()
    ram_a_sel.on()
    ram_b_sel.on()
    qspi_sd0.on()
    qspi_sd1.off()
    qspi_sd2.off()

    for i in range(10):
        clk.off()
        time.sleep(0.001)
        clk.on()
        time.sleep(0.001)

    Pin(PIN_CS,   Pin.IN, pull=Pin.PULL_UP)
    Pin(PIN_SCK,  Pin.IN, pull=Pin.PULL_DOWN)
    Pin(PIN_SD0,  Pin.IN, pull=None)
    Pin(PIN_SD1,  Pin.IN, pull=None)
    Pin(PIN_RAMA, Pin.IN, pull=Pin.PULL_UP)
    Pin(PIN_SD2,  Pin.IN, pull=None)
    Pin(PIN_RAMB, Pin.IN, pull=Pin.PULL_UP)
    Pin(PIN_SD3,  Pin.IN, pull=None)

    rst_n.on()
    time.sleep(0.001)
    clk.off()

    # Start FPGA clock and wait for firmware to execute
    clk_pwm = machine.PWM(Pin(24), freq=FPGA_CLOCK_HZ, duty_u16=32768)
    time.sleep(run_seconds)
    
    return clk_pwm, ice_creset_b


def fpga_teardown(clk_pwm, ice_creset_b):
    """Stop FPGA clock, assert reset, release QSPI bus, re-init PSRAM."""
    clk_pwm.deinit()
    Pin(24, Pin.IN, pull=Pin.PULL_DOWN)
    rst_n = Pin(12, Pin.OUT)
    rst_n.off()
    time.sleep(0.001)
    ice_creset_b.value(0)
    time.sleep(0.01)
    for p in QSPI_PINS:
        Pin(p, Pin.IN, pull=None)
    Pin(12, Pin.IN, pull=Pin.PULL_DOWN)
    run_tinyqv.setup_ram()



# --- Triangle rendering constants ---
WIDTH = HEIGHT = 32
# Triangle vertices centered at origin, scaled to 60% of half-width
_s = WIDTH * 0.3
TRI = [(0.0, -_s), (-_s, _s), (_s, _s)]


def render_all_frames(app_name='triangle'):
    """Boot FPGA, let firmware render 10 frames, read back all framebuffers."""
    t_start_all = time.ticks_ms()
    NUM_FRAMES = 1
    FRAME_FB_SIZE = WIDTH * HEIGHT * 3  # RGB words per frame
    FRAME_ZB_SIZE = WIDTH * HEIGHT       # Z-buffer words per frame
    FRAME_STRIDE = FRAME_FB_SIZE + FRAME_ZB_SIZE + 1  # FB + ZB + DONE marker

    # --- Write framebuffer dimensions to PSRAM for firmware ---
    t_psram = time.ticks_ms()
    run_tinyqv.setup_ram()

    # --- Upload texture data to PSRAM (before framebuffer, at fixed byte address) ---
    # Texture SPI base = PSRAM_IO_SPI_ADDR + TEX_PSRAM_BYTE_OFFSET (= 0x1080)
    TEX_SPI_BASE = PSRAM_IO_SPI_ADDR + TEX_PSRAM_BYTE_OFFSET
    # Select texture file per app
    if app_name == 'vkcube':
        tex_file = 'firmware_cache/borg_texture_morton.bin'
    else:
        tex_file = 'firmware_cache/test_texture_morton.bin'

    # Sentinel is at a FIXED PSRAM word (word 8 = byte offset 0x20).
    # This is well below the texture area (TEX_PSRAM_BYTE_OFFSET = 0x1080).
    # Using a fixed address means any texture upload overwrites the previous
    # app's sentinel, preventing the cross-contamination bug where a stale
    # vkcube sentinel survives a triangle run and causes vkcube to skip its
    # texture re-upload (rendering triangle's test_texture on the cube).
    TEX_SENTINEL_SPI_ADDR = PSRAM_IO_SPI_ADDR + 8 * 4  # word 8 = 0x20

    # Texture dimensions derived from file size (needed for upload loop + CRC)
    import os, binascii
    tex_size = os.stat(tex_file)[6]
    tex_n_texels = tex_size // 8  # 2 words (8 bytes) per texel in morton SPI format
    tex_dim = 1
    while tex_dim * tex_dim < tex_n_texels:
        tex_dim *= 2

    # Sentinel magic derived from the actual file content (first+last 256 bytes)
    # and the app name — so triangle and vkcube can never accidentally share
    # a sentinel even if their texture files happened to have the same CRC.
    with open(tex_file, 'rb') as _sf:
        _head = _sf.read(256)
        _sf.seek(max(0, tex_size - 256))
        _tail = _sf.read(256)
    TEX_SENTINEL_MAGIC = (binascii.crc32(_head + _tail + app_name.encode()) ^ tex_size) & 0xFFFF

    # Check if texture is already uploaded by reading the sentinel
    sm_r_check = rp2.StateMachine(0, qspi_read, 16_000_000,
                                  in_base=Pin(0), out_base=Pin(0),
                                  sideset_base=Pin(2))
    sm_r_check.active(1)
    sentinel_val = qpi_read_word(sm_r_check, TEX_SENTINEL_SPI_ADDR)
    sm_r_check.active(0)
    del sm_r_check

    sm_w = rp2.StateMachine(0, qspi_write, 16_000_000,
                            out_base=Pin(0), sideset_base=Pin(2))
    sm_w.active(1)
    qpi_write_word(sm_w, PSRAM_IO_SPI_ADDR + 0 * 4, WIDTH)
    qpi_write_word(sm_w, PSRAM_IO_SPI_ADDR + 1 * 4, HEIGHT)

    # Write default camera rotation angles to PSRAM words 2 and 3 so the firmware
    # reads them correctly on real FPGA hardware.  The PSRAM chip is NOT zero-
    # initialised between runs, so the firmware's "== 0  →  use defaults" guard in
    # borg_vkcube.c DOES NOT fire – it sees garbage floats and misuses them.
    # Both simulation targets (arcilator/main.cpp and BorgSimulator.h) explicitly
    # pre-populate these two words; do the same here.
    if app_name == 'vkcube':
        _rx_word = struct.unpack('<I', struct.pack('<f', -0.4363))[0]
        _ry_word = struct.unpack('<I', struct.pack('<f',  0.6109))[0]
        qpi_write_word(sm_w, PSRAM_IO_SPI_ADDR + 2 * 4, _rx_word)
        qpi_write_word(sm_w, PSRAM_IO_SPI_ADDR + 3 * 4, _ry_word)

    if sentinel_val == TEX_SENTINEL_MAGIC:
        print("Texture already in PSRAM (sentinel=0x%04X), skipping upload" % sentinel_val)
    else:
        try:
            TEX_WIDTH = tex_dim
            TEX_HEIGHT = tex_dim
            print("Uploading %dx%d texture (%d bytes)" % (TEX_WIDTH, TEX_HEIGHT, tex_size))

            # The .bin file is already pre-packed and Morton-ordered by the workstation
            total_words = TEX_WIDTH * TEX_HEIGHT * 2
            tex_spi_base = TEX_SPI_BASE

            with open(tex_file, 'rb') as f:
                CHUNK_TEXELS = 256
                chunk_bytes = CHUNK_TEXELS * 8
                offset = 0
                y_approx = 0
                while True:
                    data = f.read(chunk_bytes)
                    if not data: break
                    for i in range(0, len(data), 8):
                        word0 = struct.unpack_from('<I', data, i)[0]
                        word1 = struct.unpack_from('<I', data, i + 4)[0]
                        qpi_write_word(sm_w, tex_spi_base + offset, word0)
                        qpi_write_word(sm_w, tex_spi_base + offset + 4, word1)
                        offset += 8
                    y_approx += CHUNK_TEXELS // TEX_WIDTH
                    if y_approx % 32 == 0 and y_approx > 0:
                        print("  row approx %d/%d" % (y_approx, TEX_HEIGHT))

            # Write sentinel after successful upload
            qpi_write_word(sm_w, TEX_SENTINEL_SPI_ADDR, TEX_SENTINEL_MAGIC)
            print("Uploaded texture: %d words to PSRAM byte offset 0x%X in Morton order" % (total_words, TEX_PSRAM_BYTE_OFFSET))
        except Exception as e:
            print("WARNING: Could not load texture: %s" % e)

    sm_w.active(0)
    del sm_w
    print("Sent resolution %dx%d to PSRAM in %d ms" % (WIDTH, HEIGHT, time.ticks_diff(time.ticks_ms(), t_psram)))

    # Boot FPGA, test if TextureCache removed the 20s latency!
    t_fpga = time.ticks_ms()
    clk_pwm, ice_creset_b = fpga_boot(run_seconds=25)
    fpga_teardown(clk_pwm, ice_creset_b)
    print("FPGA boot/run/teardown took %d ms" % time.ticks_diff(time.ticks_ms(), t_fpga))

    # --- Read back all 10 framebuffers ---
    t_readback = time.ticks_ms()
    sm_r = rp2.StateMachine(0, qspi_read, 16_000_000,
                            in_base=Pin(0), out_base=Pin(0),
                            sideset_base=Pin(2))
    sm_r.active(1)

    out_base = PSRAM_IO_SPI_ADDR + PSRAM_OUT_OFFSET

    for frame in range(NUM_FRAMES):
        frame_base = frame * FRAME_STRIDE

        # Check DONE marker for this frame
        marker_base = frame_base + FRAME_FB_SIZE + FRAME_ZB_SIZE
        done = qpi_read_word(sm_r, out_base + marker_base * 4)
        
        t_init_lo = qpi_read_word(sm_r, out_base + (marker_base + 1) * 4)
        t_init_hi = qpi_read_word(sm_r, out_base + (marker_base + 2) * 4)
        t_init_cycles = t_init_lo | (t_init_hi << 16)
        
        t_clear_lo = qpi_read_word(sm_r, out_base + (marker_base + 3) * 4)
        t_clear_hi = qpi_read_word(sm_r, out_base + (marker_base + 4) * 4)
        t_clear_cycles = t_clear_lo | (t_clear_hi << 16)
        
        t_draw_lo = qpi_read_word(sm_r, out_base + (marker_base + 5) * 4)
        t_draw_hi = qpi_read_word(sm_r, out_base + (marker_base + 6) * 4)
        t_draw_cycles = t_draw_lo | (t_draw_hi << 16)
        
        print("Frame %d Done marker: 0x%04X" % (frame, done))
        print(" -> FW Init took:   %d cycles (%.2f ms)" % (t_init_cycles, t_init_cycles * 1000 / FPGA_CLOCK_HZ))
        print(" -> FW Clear took:  %d cycles (%.2f ms)" % (t_clear_cycles, t_clear_cycles * 1000 / FPGA_CLOCK_HZ))
        print(" -> FW Draw took:   %d cycles (%.2f ms)" % (t_draw_cycles, t_draw_cycles * 1000 / FPGA_CLOCK_HZ))

        # Read RGB framebuffer (3 FP16 words per pixel)
        fname = "/remote/%s_%02d.bin" % (app_name, frame)
        with open(fname, 'wb') as f:
            for py in range(HEIGHT):
                for px in range(WIDTH):
                    base = frame_base + (py * WIDTH + px) * 3
                    r = qpi_read_word(sm_r, out_base + (base + 0) * 4) & 0xFFFF
                    g = qpi_read_word(sm_r, out_base + (base + 1) * 4) & 0xFFFF
                    b = qpi_read_word(sm_r, out_base + (base + 2) * 4) & 0xFFFF
                    f.write(struct.pack('<HHH', r, g, b))

        print("Frame %02d (%.0f deg): %s" % (frame, frame * 36.0, fname))

    sm_r.active(0)
    del sm_r
    print("All %d frames rendered in %d ms." % (NUM_FRAMES, time.ticks_diff(time.ticks_ms(), t_readback)))
    print("Total render_all_frames time: %d ms" % time.ticks_diff(time.ticks_ms(), t_start_all))

def run_animation(firmware_bin='firmware_cache/triangle.bin'):
    """Entry point for rendering all 10 frames."""
    machine.freq(112_000_000)

    for i in range(30):
        Pin(i, Pin.IN, pull=None)

    flash_sel = Pin(17, Pin.IN, Pin.PULL_UP)
    ice_creset_b = machine.Pin(27, machine.Pin.OUT)
    ice_creset_b.value(0)

    t_prog = time.ticks_ms()
    run_tinyqv.program_firmware.program(firmware_bin)
    print("Firmware programmed in %d ms" % time.ticks_diff(time.ticks_ms(), t_prog))

    t_flash = time.ticks_ms()
    run_tinyqv.setup_flash()
    print("Flash setup in %d ms" % time.ticks_diff(time.ticks_ms(), t_flash))

    # Derive app name from firmware binary (e.g. 'firmware/vkcube.bin' -> 'vkcube')
    app_name = firmware_bin.rsplit('/', 1)[-1].replace('.bin', '')
    render_all_frames(app_name)


def run_single_frame(frame=0, firmware_bin='firmware_cache/triangle.bin'):
    """Entry point for rendering (renders all frames, kept for compatibility)."""
    run_animation(firmware_bin)

