// Generated by CIRCT firtool-1.140.0
`ifndef layers_Borg_Verification	// /home/gonsolo/work/Borg/borg/src/Borg.scala:30:7
  `define layers_Borg_Verification
`endif // not def layers_Borg_Verification
