/*
 * Copyright (c) 2024 Michael Bell
 * SPDX-License-Identifier: Apache-2.0
 */

`default_nettype none

// Generated by CIRCT firtool-1.140.0
module tt_um_tt_tinyQV(
  input  [7:0] ui_in,
  output [7:0] uo_out,
  input  [7:0] uio_in,
  output [7:0] uio_out,
               uio_oe,
  input        ena,
               clk,
               rst_n
);

  wire        _i_debug_uart_tx_uart_txd;
  wire        _i_debug_uart_tx_uart_tx_busy;
  wire [7:0]  _i_peripherals_uo_out;
  wire        _i_peripherals_audio;
  wire        _i_peripherals_audio_select;
  wire [31:0] _i_peripherals_data_out;
  wire        _i_peripherals_data_ready;
  wire [13:0] _i_peripherals_user_interrupts;
  wire [27:0] _i_tinyqv_data_addr;
  wire [1:0]  _i_tinyqv_data_write_n;
  wire [1:0]  _i_tinyqv_data_read_n;
  wire        _i_tinyqv_data_read_complete;
  wire [31:0] _i_tinyqv_data_out;
  wire [3:0]  _i_tinyqv_spi_data_out;
  wire [3:0]  _i_tinyqv_spi_data_oe;
  wire        _i_tinyqv_spi_clk_out;
  wire        _i_tinyqv_spi_flash_select;
  wire        _i_tinyqv_spi_ram_a_select;
  wire        _i_tinyqv_spi_ram_b_select;
  wire        _i_tinyqv_debug_instr_complete;
  wire        _i_tinyqv_debug_instr_ready;
  wire        _i_tinyqv_debug_instr_valid;
  wire        _i_tinyqv_debug_fetch_restart;
  wire        _i_tinyqv_debug_data_ready;
  wire        _i_tinyqv_debug_interrupt_pending;
  wire        _i_tinyqv_debug_branch;
  wire        _i_tinyqv_debug_early_branch;
  wire        _i_tinyqv_debug_ret;
  wire        _i_tinyqv_debug_reg_wen;
  wire        _i_tinyqv_debug_counter_0;
  wire        _i_tinyqv_debug_data_continue;
  wire        _i_tinyqv_debug_stall_txn;
  wire        _i_tinyqv_debug_stop_txn;
  wire [3:0]  _i_tinyqv_debug_rd;
  wire        _rst_reg_n_T_2 = ~clk;
  reg         rst_reg_n;
  reg  [7:0]  ui_in_sync0;
  reg  [7:0]  ui_in_sync;
  wire [3:0]  connect_peripheral =
    {_i_tinyqv_data_addr[27:6], _i_tinyqv_data_addr[1:0]} == 24'h800000
      ? _i_tinyqv_data_addr[5:2]
      : {4{_i_tinyqv_data_addr[27:11] == 17'h10000}};
  reg  [1:0]  gpio_out_sel;
  reg  [4:0]  time_limit;
  wire        _debug_signals_T_1 = _i_tinyqv_data_write_n != 2'h3;
  wire        _GEN = connect_peripheral == 4'h3;
  wire        _GEN_0 = connect_peripheral == 4'hB;
  reg  [6:0]  time_count;
  wire        time_pulse = time_count == {time_limit, 2'h3};
  reg         debug_register_data;
  reg  [3:0]  debug_rd_r;
  wire [15:0] _debug_signal_T_1 =
    {_i_tinyqv_debug_instr_complete,
     _i_tinyqv_debug_instr_ready,
     _i_tinyqv_debug_instr_valid,
     _i_tinyqv_debug_fetch_restart,
     _i_tinyqv_data_read_n != 2'h3,
     _debug_signals_T_1,
     _i_tinyqv_debug_data_ready,
     _i_tinyqv_debug_interrupt_pending,
     _i_tinyqv_debug_branch,
     _i_tinyqv_debug_early_branch,
     _i_tinyqv_debug_ret,
     _i_tinyqv_debug_reg_wen,
     _i_tinyqv_debug_counter_0,
     _i_tinyqv_debug_data_continue,
     _i_tinyqv_debug_stall_txn,
     _i_tinyqv_debug_stop_txn} >> ui_in[6:3];
  always @(posedge _rst_reg_n_T_2)
    rst_reg_n <= rst_n;
  always @(posedge clk) begin
    ui_in_sync0 <= ui_in;
    ui_in_sync <= ui_in_sync0;
    debug_rd_r <= _i_tinyqv_debug_rd;
    if (~rst_reg_n) begin
      gpio_out_sel <= {~(ui_in[0]), 1'h0};
      time_limit <= 5'hF;
      time_count <= 7'h0;
      debug_register_data <= ui_in[1];
    end
    else begin
      if (_debug_signals_T_1 & _GEN)
        gpio_out_sel <= _i_tinyqv_data_out[7:6];
      if (_debug_signals_T_1 & _GEN_0)
        time_limit <= _i_tinyqv_data_out[6:2];
      time_count <= time_pulse ? 7'h0 : time_count + 7'h1;
      if (_debug_signals_T_1 & connect_peripheral == 4'hC)
        debug_register_data <= _i_tinyqv_data_out[0];
    end
  end // always @(posedge)
  tinyQV i_tinyqv (
    .clk                     (clk),
    .rstn                    (rst_reg_n),
    .data_addr               (_i_tinyqv_data_addr),
    .data_write_n            (_i_tinyqv_data_write_n),
    .data_read_n             (_i_tinyqv_data_read_n),
    .data_read_complete      (_i_tinyqv_data_read_complete),
    .data_out                (_i_tinyqv_data_out),
    .data_ready              (connect_peripheral != 4'hF | _i_peripherals_data_ready),
    .data_in
      (connect_peripheral == 4'h2
         ? 32'h41
         : _GEN
             ? {24'h0, gpio_out_sel, 6'h0}
             : connect_peripheral == 4'h7
                 ? {31'h0, _i_debug_uart_tx_uart_tx_busy}
                 : _GEN_0
                     ? {25'h0, time_limit, 2'h3}
                     : (&connect_peripheral) ? _i_peripherals_data_out : 32'hFFFFFFFF),
    .interrupt_req           ({_i_peripherals_user_interrupts, ui_in_sync[1:0]}),
    .time_pulse              (time_pulse),
    .spi_data_in             ({uio_in[5:4], uio_in[2:1]}),
    .spi_data_out            (_i_tinyqv_spi_data_out),
    .spi_data_oe             (_i_tinyqv_spi_data_oe),
    .spi_clk_out             (_i_tinyqv_spi_clk_out),
    .spi_flash_select        (_i_tinyqv_spi_flash_select),
    .spi_ram_a_select        (_i_tinyqv_spi_ram_a_select),
    .spi_ram_b_select        (_i_tinyqv_spi_ram_b_select),
    .debug_instr_complete    (_i_tinyqv_debug_instr_complete),
    .debug_instr_ready       (_i_tinyqv_debug_instr_ready),
    .debug_instr_valid       (_i_tinyqv_debug_instr_valid),
    .debug_fetch_restart     (_i_tinyqv_debug_fetch_restart),
    .debug_data_ready        (_i_tinyqv_debug_data_ready),
    .debug_interrupt_pending (_i_tinyqv_debug_interrupt_pending),
    .debug_branch            (_i_tinyqv_debug_branch),
    .debug_early_branch      (_i_tinyqv_debug_early_branch),
    .debug_ret               (_i_tinyqv_debug_ret),
    .debug_reg_wen           (_i_tinyqv_debug_reg_wen),
    .debug_counter_0         (_i_tinyqv_debug_counter_0),
    .debug_data_continue     (_i_tinyqv_debug_data_continue),
    .debug_stall_txn         (_i_tinyqv_debug_stall_txn),
    .debug_stop_txn          (_i_tinyqv_debug_stop_txn),
    .debug_rd                (_i_tinyqv_debug_rd)
  );
  tinyQV_peripherals #(
    .CLOCK_MHZ(64)
  ) i_peripherals (
    .clk                (clk),
    .rst_n              (rst_reg_n),
    .ui_in              (ui_in_sync),
    .ui_in_raw          (ui_in),
    .uo_out             (_i_peripherals_uo_out),
    .audio              (_i_peripherals_audio),
    .audio_select       (_i_peripherals_audio_select),
    .addr_in            (_i_tinyqv_data_addr[10:0]),
    .data_in            (_i_tinyqv_data_out),
    .data_write_n       (_i_tinyqv_data_write_n),
    .data_read_n        (_i_tinyqv_data_read_n),
    .data_out           (_i_peripherals_data_out),
    .data_ready         (_i_peripherals_data_ready),
    .data_read_complete (_i_tinyqv_data_read_complete),
    .user_interrupts    (_i_peripherals_user_interrupts)
  );
  uart_tx #(
    .BIT_RATE(4000000),
    .CLK_HZ(64000000)
  ) i_debug_uart_tx (
    .clk          (clk),
    .resetn       (rst_reg_n),
    .uart_txd     (_i_debug_uart_tx_uart_txd),
    .uart_tx_en   (_debug_signals_T_1 & connect_peripheral == 4'h6),
    .uart_tx_data (_i_tinyqv_data_out[7:0]),
    .uart_tx_busy (_i_debug_uart_tx_uart_tx_busy)
  );
  assign uo_out =
    {gpio_out_sel[1] ? _i_peripherals_uo_out[7] : _debug_signal_T_1[0],
     gpio_out_sel[0] ? _i_peripherals_uo_out[6] : _i_debug_uart_tx_uart_txd,
     debug_register_data ? debug_rd_r[3] : _i_peripherals_uo_out[5],
     debug_register_data ? debug_rd_r[2] : _i_peripherals_uo_out[4],
     debug_register_data ? debug_rd_r[1] : _i_peripherals_uo_out[3],
     debug_register_data ? debug_rd_r[0] : _i_peripherals_uo_out[2],
     _i_peripherals_uo_out[1:0]};
  assign uio_out =
    {_i_peripherals_audio_select ? _i_peripherals_audio : _i_tinyqv_spi_ram_b_select,
     _i_tinyqv_spi_ram_a_select,
     _i_tinyqv_spi_data_out[3:2],
     _i_tinyqv_spi_clk_out,
     _i_tinyqv_spi_data_out[1:0],
     _i_tinyqv_spi_flash_select};
  assign uio_oe =
    rst_n
      ? {2'h3, _i_tinyqv_spi_data_oe[3:2], 1'h1, _i_tinyqv_spi_data_oe[1:0], 1'h1}
      : 8'h0;
endmodule



// Generated by CIRCT firtool-1.140.0


// Generated by CIRCT firtool-1.140.0


// Generated by CIRCT firtool-1.140.0


// Generated by CIRCT firtool-1.140.0