// Generated by CIRCT firtool-1.140.0
module tinyQV_peripherals(
  input         clk,
                rst_n,
  input  [7:0]  ui_in,
                ui_in_raw,
  output [7:0]  uo_out,
  output        audio,
                audio_select,
  input  [10:0] addr_in,
  input  [31:0] data_in,
  input  [1:0]  data_write_n,
                data_read_n,
  output [31:0] data_out,
  output        data_ready,
  input         data_read_complete,
  output [13:0] user_interrupts
);

  wire [7:0]  _i_user_peri39_io_uo_out;
  wire [31:0] _i_user_peri39_io_data_out;
  wire        _i_user_peri39_io_data_ready;
  wire [7:0]  _i_uart_uo_out;
  wire [31:0] _i_uart_data_out;
  wire        _i_uart_data_ready;
  wire [1:0]  _i_uart_user_interrupt;
  reg  [31:0] data_out_r;
  reg         data_out_hold;
  reg         data_ready_r;
  wire [1:0]  data_read_n_peri = data_read_n | {2{data_ready_r}};
  wire        _data_ready_T = data_write_n != 2'h3;
  wire [15:0] _peri_user_T = 16'h1 << addr_in[9:6];
  wire [22:0] peri_user =
    addr_in[10] | addr_in[9]
      ? {(&(addr_in[10:9])) | addr_in[10:6] == 5'h17, 22'h0}
      : {8'h0, _peri_user_T[15:1]};
  reg  [7:0]  gpio_out;
  reg  [5:0]  func_sel_0;
  reg  [5:0]  func_sel_1;
  reg  [5:0]  func_sel_2;
  reg  [5:0]  func_sel_3;
  reg  [5:0]  func_sel_4;
  reg  [5:0]  func_sel_5;
  reg  [5:0]  func_sel_6;
  reg  [5:0]  func_sel_7;
  wire        data_ready_from_peri =
    peri_user[22] ? _i_user_peri39_io_data_ready : ~(peri_user[1]) | _i_uart_data_ready;
  wire        read_req = data_read_n != 2'h3;
  wire        _GEN = ~data_out_hold & data_ready_from_peri & read_req;
  wire        _GEN_0 = addr_in[5:0] == 6'h0;
  wire        _GEN_1 = addr_in[5] & addr_in[1:0] == 2'h0 & _data_ready_T;
  always @(posedge clk) begin
    if (~rst_n) begin
      data_out_r <= 32'h0;
      data_out_hold <= 1'h0;
      data_ready_r <= 1'h0;
      gpio_out <= 8'h0;
      func_sel_0 <= 6'h2;
      func_sel_1 <= 6'h2;
      func_sel_2 <= 6'h1;
      func_sel_3 <= 6'h1;
      func_sel_4 <= 6'h1;
      func_sel_5 <= 6'h1;
      func_sel_6 <= 6'h1;
      func_sel_7 <= 6'h1;
    end
    else begin
      if (_GEN)
        data_out_r <=
          peri_user[22]
            ? _i_user_peri39_io_data_out
            : peri_user[1]
                ? _i_uart_data_out
                : peri_user[0]
                    ? (_GEN_0
                         ? {24'h0, gpio_out}
                         : addr_in[5:0] == 6'h4 ? {24'h0, ui_in} : 32'h0)
                    : 32'h0;
      data_out_hold <= _GEN | ~data_read_complete & data_out_hold;
      data_ready_r <= read_req & data_ready_from_peri;
      if (peri_user[0] & _GEN_0 & _data_ready_T)
        gpio_out <= data_in[7:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h0)
        func_sel_0 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h1)
        func_sel_1 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h2)
        func_sel_2 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h3)
        func_sel_3 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h4)
        func_sel_4 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h5)
        func_sel_5 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & addr_in[4:2] == 3'h6)
        func_sel_6 <= data_in[5:0];
      if (peri_user[0] & _GEN_1 & (&(addr_in[4:2])))
        func_sel_7 <= data_in[5:0];
    end
  end // always @(posedge)
  tqvp_uart_wrapper #(
    .CLOCK_MHZ(64)
  ) i_uart (
    .clk            (clk),
    .rst_n          (rst_n),
    .ui_in          (ui_in),
    .uo_out         (_i_uart_uo_out),
    .address        (addr_in[5:0]),
    .data_in        (data_in),
    .data_write_n   (data_write_n | {2{~(peri_user[1])}}),
    .data_read_n    (data_read_n_peri | {2{~(peri_user[1])}}),
    .data_out       (_i_uart_data_out),
    .data_ready     (_i_uart_data_ready),
    .user_interrupt (_i_uart_user_interrupt)
  );
  Borg i_user_peri39 (
    .clock           (clk),
    .reset           (~rst_n),
    .io_ui_in        (ui_in),
    .io_uo_out       (_i_user_peri39_io_uo_out),
    .io_address      (addr_in[5:0]),
    .io_data_in      (data_in),
    .io_data_write_n (data_write_n | {2{~(peri_user[22])}}),
    .io_data_read_n  (data_read_n_peri | {2{~(peri_user[22])}}),
    .io_data_out     (_i_user_peri39_io_data_out),
    .io_data_ready   (_i_user_peri39_io_data_ready)
  );
  assign uo_out =
    {func_sel_7 == 6'h17
       ? _i_user_peri39_io_uo_out[7]
       : func_sel_7 == 6'h2 ? _i_uart_uo_out[7] : gpio_out[7],
     func_sel_6 == 6'h17
       ? _i_user_peri39_io_uo_out[6]
       : func_sel_6 == 6'h2 ? _i_uart_uo_out[6] : gpio_out[6],
     func_sel_5 == 6'h17
       ? _i_user_peri39_io_uo_out[5]
       : func_sel_5 == 6'h2 ? _i_uart_uo_out[5] : gpio_out[5],
     func_sel_4 == 6'h17
       ? _i_user_peri39_io_uo_out[4]
       : func_sel_4 == 6'h2 ? _i_uart_uo_out[4] : gpio_out[4],
     func_sel_3 == 6'h17
       ? _i_user_peri39_io_uo_out[3]
       : func_sel_3 == 6'h2 ? _i_uart_uo_out[3] : gpio_out[3],
     func_sel_2 == 6'h17
       ? _i_user_peri39_io_uo_out[2]
       : func_sel_2 == 6'h2 ? _i_uart_uo_out[2] : gpio_out[2],
     func_sel_1 == 6'h17
       ? _i_user_peri39_io_uo_out[1]
       : func_sel_1 == 6'h2 ? _i_uart_uo_out[1] : gpio_out[1],
     func_sel_0 == 6'h17
       ? _i_user_peri39_io_uo_out[0]
       : func_sel_0 == 6'h2 ? _i_uart_uo_out[0] : gpio_out[0]};
  assign audio = 1'h0;
  assign audio_select = 1'h0;
  assign data_out = data_out_r;
  assign data_ready = data_ready_r | _data_ready_T;
  assign user_interrupts = {12'h0, _i_uart_user_interrupt};
endmodule

