// SPDX-FileCopyrightText: © 2025-2026 Andreas Wendleder
// SPDX-License-Identifier: GPL-3.0-or-later

// Borg GPU driver — pipeline orchestration, hardware init, draw commands.

#include "borg_driver.h"
#include "borg_fpu.h"
#include "borg_math.h"
#include "borg_raster.h"
#include "borg_spirb.h"
#include <stdbool.h>
#include <stdint.h>


// @doc:mmio-map
#include "borg_mmio.h" // Auto-generated by MmioMap.scala
// @doc:end
#include "borg_gpu_regs.h"

#define FP16_SIXTEEN 0x4C00

static inline void fb_write_pixel(int base, rgb16_t c) {
  PSRAM_OUT(base + 0) = c.r;
  PSRAM_OUT(base + 1) = c.g;
  PSRAM_OUT(base + 2) = c.b;
}



static inline rgb16_t fb_read_texel(int base) {
  return (rgb16_t){PSRAM_IN(base + 0), PSRAM_IN(base + 1), PSRAM_IN(base + 2)};
}

typedef struct {
  int w, h;
} dim2_t;

typedef struct {
  int psram_offset;        // -1 = no texture
  dim2_t size;             // integer dimensions
  uint16_t w_fp16, h_fp16; // FP16 dimensions for Borg FPU
} texture_t;

// Runtime framebuffer dimensions and derived values
int borg_fb_width;
int borg_fb_height;
static fp16_t fp16_half_width;
static fp16_t pc_lut[BORG_MAX_FB_DIM];

#define NUM_VERTICES 3
#define MAX_CLIP_VERTS 4 // Clipping one triangle can produce at most a quad

// Clipped vertex: carries all interpolable attributes through clipping.
typedef struct {
  fp16_t x, y, z, w; // clip-space position
  fp16_t r, g, b;    // vertex color
  fp16_t u, v;       // texture UV
} clip_vertex_t;

// Integer bounding box (clamped to framebuffer).
typedef struct { int x0, y0, x1, y1; } bbox_t;


// Global timing vars
unsigned int t_init_cycles = 0;
unsigned int t_clear_cycles = 0;
unsigned int t_draw_cycles = 0;

// --- Texture state ---
static texture_t tex = {.psram_offset = -1};

// --- UART ---
void putc_uart(int c) {
  while (UART_STATUS & 1)
    ;
  UART_TX = c;
}

static void puts_uart(const char *s) {
  while (*s)
    putc_uart(*s++);
}


// --- Timing and debug printing ---
static inline unsigned int get_cycles(void) {
  unsigned int cycles;
  __asm__ volatile("csrr %0, cycle" : "=r"(cycles));
  return cycles;
}

// --- Shader globals ---
static spirb_shader_t vert_shader;
static spirb_shader_t rast_shader;
static spirb_shader_t frag_shader;

// --- Vertex shader ---
static void run_vertex_shader(const fp16_t *uniforms, const fp16_t *attrs,
                              fp16_t *outputs) {
  const spirb_shader_t *s = &vert_shader;
  borg_load_spirb_shader(s);

  for (int i = 0; i < s->num_uniforms; i++)
    BORG_GPU->uniform[s->uniform_regs[i]] = uniforms[i];

  for (int v = 0; v < NUM_VERTICES; v++) {
    BORG_GPU->control = CONTROL_REG_T__RESET_PIPELINE_bm;
    for (int i = 0; i < s->num_uniforms; i++)
      BORG_GPU->uniform[s->uniform_regs[i]] = uniforms[i];
    for (int i = 0; i < s->num_attributes; i++)
      BORG_GPU->gpr[s->attribute_regs[i]] = attrs[v * s->num_attributes + i];
    for (int i = 0; i < s->num_consts; i++)
      BORG_GPU->gpr[s->const_regs[i]] = s->const_vals[i];
    borg_run(BORG_IMEM_VERT_OFFSET);
    for (int i = 0; i < s->num_outputs; i++)
      outputs[v * s->num_outputs + i] = BORG_GPU->gpr[s->output_regs[i]] & 0xFFFF;
  }
}

// --- Public API ---


void borgCreateDevice(void) {
  STARTUP_DELAY();
  UART_BAUD = UART_BAUD_DEFAULT;
  puts_uart("Borg pipeline\r\n");
  unsigned int t_init = get_cycles();

  // Read framebuffer dimensions from PSRAM (written by host)
  borg_fb_width = PSRAM_IN(0);
  borg_fb_height = PSRAM_IN(1);
  if (borg_fb_width == 0) borg_fb_width = 32;
  if (borg_fb_height == 0) borg_fb_height = 32;

  // Compute FP16 half-width for NDC→screen transform
  int hw = borg_fb_width / 2;
  int exp = 0;
  int tmp = hw;
  while (tmp > 1) {
    tmp >>= 1;
    exp++;
  }
  fp16_half_width = ((exp + 15) << 10);

  // Compute pixel center LUT: 0.5, 1.5, ..., (width-0.5)
  fp16_t val = FP16_HALF;
  for (int i = 0; i < borg_fb_width; i++) {
    pc_lut[i] = val;
    val = borg_fp16_add(val, FP16_ONE);
  }
  t_init_cycles = get_cycles() - t_init;
}

void borgCreateGraphicsPipeline(const BorgShaderModule *vert,
                                const BorgShaderModule *rast,
                                const BorgShaderModule *frag) {
  spirb_parse(vert->code, &vert_shader);
  spirb_parse(rast->code, &rast_shader);
  spirb_parse(frag->code, &frag_shader);
}

void borg_set_angle(borg_draw_data_t *d, fp16_t angle_fp16) {
  // Compute vertex shader uniforms from angle for Phase 2 4x4 Projection
  fp16_t s = fp16_sin(angle_fp16);
  fp16_t c = fp16_cos(angle_fp16);
  fp16_t ns = fp16_neg(s);

  // Col 0 (X)
  d->uniforms[0] = c;
  d->uniforms[1] = s;
  d->uniforms[2] = FP16_ZERO;
  d->uniforms[3] = FP16_ZERO;

  // Col 1 (Y)
  d->uniforms[4] = ns;
  d->uniforms[5] = c;
  d->uniforms[6] = FP16_ZERO;
  d->uniforms[7] = FP16_ZERO;

  // Col 2 (Z) - passed through seamlessly
  d->uniforms[8] = FP16_ZERO;
  d->uniforms[9] = FP16_ZERO;
  d->uniforms[10] = FP16_ONE;
  d->uniforms[11] = FP16_ZERO;

  // Col 3 (Translations/W)
  d->uniforms[12] = FP16_ZERO;
  d->uniforms[13] = FP16_ZERO;
  d->uniforms[14] = FP16_ZERO;
  d->uniforms[15] = FP16_ONE;
}

#define FRAME_FB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT * 3) // RGB words
#define FRAME_ZB_SIZE (BORG_FB_WIDTH * BORG_FB_HEIGHT)     // Z-buffer words
#define FRAME_STRIDE                                                           \
  (FRAME_FB_SIZE + FRAME_ZB_SIZE + 1) // FB + ZB + DONE marker

void borg_clear_zbuffer(int frame) {
  unsigned int t_start = get_cycles();
  int fb_offset = frame * FRAME_STRIDE;
  int zb_offset = fb_offset + FRAME_FB_SIZE;
  // Clear RGB framebuffer to black
  for (int i = 0; i < FRAME_FB_SIZE; i++)
    PSRAM_OUT(fb_offset + i) = 0;
  // Clear z-buffer to max depth
  for (int i = 0; i < FRAME_ZB_SIZE; i++)
    PSRAM_OUT(zb_offset + i) = FP16_MAX_DEPTH;
  t_clear_cycles = get_cycles() - t_start;
}

void borg_set_texture(int psram_offset, int width, int height) {
  tex = (texture_t){.psram_offset = psram_offset,
                    .size = {width, height},
                    .w_fp16 = uint_to_fp16(width),
                    .h_fp16 = uint_to_fp16(height)};
}

void borg_clear_texture(void) { tex.psram_offset = -1; }

static void shade_and_write_pixel(int frame, int px, int py, rgb16_t color,
                                  fp16_t z, uv16_t uv_interp,
                                  const texture_t *t) {
  // Depth test: read current z, compare (closer = smaller).
  // Skip pixels with negative Z (behind camera) — their sign bit would
  // corrupt the unsigned Z-buffer comparison.
  if (!fp16_ge_zero(z))
    return;
  int zb_idx = frame * FRAME_STRIDE + FRAME_FB_SIZE + (py * BORG_FB_WIDTH + px);
  fp16_t old_z = PSRAM_OUT(zb_idx);
  if (z >= old_z)
    return;
  PSRAM_OUT(zb_idx) = z;

  // Texture sampling: replace vertex colors with texel
  if (t->psram_offset >= 0) {
    texcoord_t tc = uv_to_texcoord(uv_interp, t->w_fp16, t->h_fp16);
    if (tc.x >= t->size.w)
      tc.x = t->size.w - 1;
    if (tc.y >= t->size.h)
      tc.y = t->size.h - 1;
    int morton_idx = morton_encode(tc.x, tc.y);
    int texel = t->psram_offset + morton_idx * 3;
    color = fb_read_texel(texel);
  }

  int base = frame * FRAME_STRIDE + (py * BORG_FB_WIDTH + px) * 3;
  fb_write_pixel(base, color);
}

// --- Triangle Clipping (Step 6) ---

// Linearly interpolate between two clip vertices: result = a + t * (b - a)
static clip_vertex_t clip_lerp(const clip_vertex_t *a, const clip_vertex_t *b,
                               fp16_t t) {
  clip_vertex_t out;
  // For each component: out = a + t * (b - a) = fmadd(t, b-a, a)
  out.x = borg_fp16_fmadd(t, BORG_FP16_SUB(b->x, a->x), a->x);
  out.y = borg_fp16_fmadd(t, BORG_FP16_SUB(b->y, a->y), a->y);
  out.z = borg_fp16_fmadd(t, BORG_FP16_SUB(b->z, a->z), a->z);
  out.w = borg_fp16_fmadd(t, BORG_FP16_SUB(b->w, a->w), a->w);
  out.r = borg_fp16_fmadd(t, BORG_FP16_SUB(b->r, a->r), a->r);
  out.g = borg_fp16_fmadd(t, BORG_FP16_SUB(b->g, a->g), a->g);
  out.b = borg_fp16_fmadd(t, BORG_FP16_SUB(b->b, a->b), a->b);
  out.u = borg_fp16_fmadd(t, BORG_FP16_SUB(b->u, a->u), a->u);
  out.v = borg_fp16_fmadd(t, BORG_FP16_SUB(b->v, a->v), a->v);
  return out;
}

// Clip polygon against near plane (z >= 0 in clip space).
// Sutherland-Hodgman: vertices with z < 0 are outside.
// Returns number of output vertices (0..MAX_CLIP_VERTS).
static int clip_near(const clip_vertex_t *in, int n_in, clip_vertex_t *out) {
  int n_out = 0;
  for (int i = 0; i < n_in; i++) {
    int prev_idx = (i == 0) ? n_in - 1 : i - 1;
    const clip_vertex_t *cur = &in[i];
    const clip_vertex_t *prev = &in[prev_idx];
    int cur_inside = fp16_ge_zero(cur->z);
    int prev_inside = fp16_ge_zero(prev->z);
    if (cur_inside != prev_inside) {
      // Edge crosses the near plane — compute intersection.
      // t = prev.z / (prev.z - cur.z)
      fp16_t denom = BORG_FP16_SUB(prev->z, cur->z);
      fp16_t t = borg_fp16_mul(prev->z, borg_fp16_rcp(denom));
      out[n_out++] = clip_lerp(prev, cur, t);
    }
    if (cur_inside)
      out[n_out++] = *cur;
  }
  return n_out;
}

// Clip polygon against far plane (z <= w in clip space).
// Sutherland-Hodgman: vertices with z > w are outside.
// Returns number of output vertices (0..MAX_CLIP_VERTS+1, capped at 7 for a
// triangle).
static int clip_far(const clip_vertex_t *in, int n_in, clip_vertex_t *out) {
  int n_out = 0;
  for (int i = 0; i < n_in; i++) {
    int prev_idx = (i == 0) ? n_in - 1 : i - 1;
    const clip_vertex_t *cur = &in[i];
    const clip_vertex_t *prev = &in[prev_idx];
    // signed distance to far plane: d = w - z (inside when d >= 0)
    fp16_t d_cur = BORG_FP16_SUB(cur->w, cur->z);
    fp16_t d_prev = BORG_FP16_SUB(prev->w, prev->z);
    int cur_inside = fp16_ge_zero(d_cur);
    int prev_inside = fp16_ge_zero(d_prev);
    if (cur_inside != prev_inside) {
      // t = d_prev / (d_prev - d_cur)
      fp16_t denom = BORG_FP16_SUB(d_prev, d_cur);
      fp16_t t = borg_fp16_mul(d_prev, borg_fp16_rcp(denom));
      out[n_out++] = clip_lerp(prev, cur, t);
    }
    if (cur_inside)
      out[n_out++] = *cur;
  }
  return n_out;
}

// Compute screen-space AABB of 3 vertices, clamped to framebuffer.
static bbox_t compute_bbox(const xy16x3_t *pos) {
  fp16_t min_x = pos->v[0].x, max_x = pos->v[0].x;
  fp16_t min_y = pos->v[0].y, max_y = pos->v[0].y;
  for (int i = 1; i < 3; i++) {
    if (fp16_lt(pos->v[i].x, min_x)) min_x = pos->v[i].x;
    if (fp16_lt(max_x, pos->v[i].x)) max_x = pos->v[i].x;
    if (fp16_lt(pos->v[i].y, min_y)) min_y = pos->v[i].y;
    if (fp16_lt(max_y, pos->v[i].y)) max_y = pos->v[i].y;
  }
  int x0 = fp16_ge_zero(min_x) ? fp16_to_uint(min_x) : 0;
  int y0 = fp16_ge_zero(min_y) ? fp16_to_uint(min_y) : 0;
  int x1 = fp16_ge_zero(max_x) ? fp16_to_uint(max_x) + 1 : 0;
  int y1 = fp16_ge_zero(max_y) ? fp16_to_uint(max_y) + 1 : 0;
  if (x1 > BORG_FB_WIDTH)  x1 = BORG_FB_WIDTH;
  if (y1 > BORG_FB_HEIGHT) y1 = BORG_FB_HEIGHT;
  return (bbox_t){ x0, y0, x1, y1 };
}

// Iterate all pixels within the triangle's bounding box via hardware counters.
// Step 10.6.5: Auto-chain integration — load all uniforms (rast u0-u11 + frag
// u12-u30) once per triangle, then the hardware FSM chains rasterizer -> fragment
// without CPU involvement.  Eliminates per-pixel uniform reloading and the
// manual borg_run_fragment() call.
static int current_uniform_page = 0;

static void shade_tiles(const triangle_t *tri, const texture_t *t, int frame) {
  bbox_t bb = compute_bbox(&tri->screen_pos);

  PSRAM_OUT(5003) = 0x2222;
  PSRAM_OUT(5004) = bb.x0;
  PSRAM_OUT(5005) = bb.y0;
  PSRAM_OUT(5006) = bb.x1;
  PSRAM_OUT(5007) = bb.y1;

  // Ping-pong the uniform pages (Step 13.4)
  current_uniform_page ^= 1;
  BORG_GPU->control = (current_uniform_page << CONTROL_REG_T__UNIFORM_WRITE_PAGE_bp);

  // --- Load ALL uniforms once per triangle ---
  // Rasterizer uniforms (u0-u11): edge constants + negated vertex positions
  borg_load_edge_constants(&rast_shader, tri->edges.v);
  for (int i = 0; i < 3; i++) {
    BORG_GPU->uniform[rast_shader.uniform_regs[6 + i * 2 + 0]] = BORG_FP16_NEG(tri->screen_pos.v[i].x);
    BORG_GPU->uniform[rast_shader.uniform_regs[6 + i * 2 + 1]] = BORG_FP16_NEG(tri->screen_pos.v[i].y);
  }

  // Fragment uniforms (u12-u30): inv_area, vertex colors, z, UV
  const rgb16_t *colors = tri->colors.v;
  BORG_GPU->uniform[frag_shader.uniform_regs[0]] = tri->inv_area;

  if (tri->has_uvs) {
    const uv16_t *uvs = tri->uvs.v;
    // Map U and V into the R and G uniforms
    // This allows the hardware tile buffer's R/G slots to temporarily hold U/V!
    load_uniform_triple(&frag_shader, 1, uvs[0].u, uvs[1].u, uvs[2].u);
    load_uniform_triple(&frag_shader, 4, uvs[0].v, uvs[1].v, uvs[2].v);
    load_uniform_triple(&frag_shader, 7, 0, 0, 0); // B unused
    for (int i = 13; i <= 18; i++)
      BORG_GPU->uniform[frag_shader.uniform_regs[i]] = 0;
  } else {
    load_uniform_triple(&frag_shader, 1, colors[0].r, colors[1].r, colors[2].r);
    load_uniform_triple(&frag_shader, 4, colors[0].g, colors[1].g, colors[2].g);
    load_uniform_triple(&frag_shader, 7, colors[0].b, colors[1].b, colors[2].b);
    for (int i = 13; i <= 18; i++)
      BORG_GPU->uniform[frag_shader.uniform_regs[i]] = 0;
  }

  load_uniform_triple(&frag_shader, 10, tri->z_vals.v[0], tri->z_vals.v[1],
                       tri->z_vals.v[2]);

  // 4x4 Tiling loop (Step 11.4): subdivide bbox into 4x4 tiles
  for (int ty = bb.y0 & ~3; ty < bb.y1; ty += 4) {
    for (int tx = bb.x0 & ~3; tx < bb.x1; tx += 4) {
      
      // Compute clamped 4x4 sub-bbox for this tile
      int min_x = (tx > bb.x0) ? tx : bb.x0;
      int min_y = (ty > bb.y0) ? ty : bb.y0;
      int max_x = ((tx + 4) < bb.x1) ? (tx + 4) : bb.x1;
      int max_y = ((ty + 4) < bb.y1) ? (ty + 4) : bb.y1;
      
      // If tile is completely outside bbox, skip
      if (min_x >= max_x || min_y >= max_y) continue;

      // Wait for space in the command FIFO
      while (BORG_GPU->status & STATUS_REG_T__FIFO_FULL_bm);

      // Enqueue the command for this hardware tile
      uint32_t cmd = (min_x << CMD_ENQUEUE_REG_T__BBOX_MIN_X_bp) |
                     (min_y << CMD_ENQUEUE_REG_T__BBOX_MIN_Y_bp) |
                     (max_x << CMD_ENQUEUE_REG_T__BBOX_MAX_X_bp) |
                     (max_y << CMD_ENQUEUE_REG_T__BBOX_MAX_Y_bp) |
                     (BORG_IMEM_FRAG_OFFSET << CMD_ENQUEUE_REG_T__FRAG_PC_bp) |
                     (current_uniform_page << CMD_ENQUEUE_REG_T__UNIFORM_PAGE_bp);
      BORG_GPU->cmd_enqueue = cmd;

      // Hardware needs a few cycles to pop from FIFO and start the tile
      for (volatile int k=0; k<16; k++) { __asm__ volatile("nop"); }

      // Clear the tile buffer (write 1 to bit 4 of tile_ctrl)
      BORG_GPU->tile_ctrl = TILE_CTRL_REG_T__CLEAR_bm;
      
      uint32_t active_pixels = 0;
      do {
        uint32_t iter = BORG_GPU->iter;
        if (!(iter & ITER_REG_T__VALID_bm)) break;

        // BORG_GPU->iter write advances the iterator by one pixel
        BORG_GPU->iter = 1;

        if (iter & ITER_REG_T__INSIDE_FLAG_bm) {
            active_pixels++;
        }
      } while (1);

      if (active_pixels > 0) {
        // Only flush tile buffer to PSRAM if something was drawn
        for (uint32_t tile_idx = 0; tile_idx < 16; tile_idx++) {
          // Set read index in TILE_CTRL
          BORG_GPU->tile_ctrl = tile_idx;
          
          uint32_t rg = BORG_GPU->tile_rg;
          uint32_t bz = BORG_GPU->tile_bz;
          
          int abs_x = (tile_idx & 3) + tx;
          int abs_y = (tile_idx >> 2) + ty;
          
          if (abs_x < min_x || abs_x >= max_x || abs_y < min_y || abs_y >= max_y) continue;
          
          fp16_t z = bz & 0xFFFF;
          if (z >= FP16_MAX_DEPTH) continue; // Fragment was not shaded or was outside!
          puts_uart("P");

          // The tile buffer stores U/V in R/G when textured, or R/G in R/G when untextured.
          if (tri->has_uvs) {
            uv16_t uv = {rg >> 16, rg & 0xFFFF}; // U from R, V from G
            rgb16_t stub_color = {0,0,0}; // Overwritten by texel fetch
            shade_and_write_pixel(frame, abs_x, abs_y, stub_color, z, uv, t);
          } else {
            rgb16_t color = {rg >> 16, rg & 0xFFFF, bz >> 16};
            uv16_t stub_uv = {0, 0};
            shade_and_write_pixel(frame, abs_x, abs_y, color, z, stub_uv, t);
          }
        }
      }
    }
  }

  // Disable chaining after triangle (no longer need to clear register, handled per-command)
}


// Clip-space → NDC → screen-space for 3 vertices.
static void perspective_divide(const clip_vertex_t *cv,
                               fp16_t ndc[3][3], xy16x3_t *pos) {
  for (int v = 0; v < 3; v++) {
    fp16_t inv_w = borg_fp16_rcp(cv[v].w);
    ndc[v][0] = borg_fp16_mul(cv[v].x, inv_w);
    ndc[v][1] = borg_fp16_mul(cv[v].y, inv_w);
    ndc[v][2] = borg_fp16_mul(cv[v].z, inv_w);
    pos->v[v] = (xy16_t){
      borg_fp16_fmadd(ndc[v][0], fp16_half_width, fp16_half_width),
      borg_fp16_fmadd(ndc[v][1], fp16_half_width, fp16_half_width)
    };
  }
}

// Triangle setup: compute signed area, back-face cull, return inv_area.
// Returns 0 if the triangle is degenerate or back-facing.
static int triangle_setup(const xy16x3_t *pos, fp16_t *inv_area) {
  fp16_t dx10 = BORG_FP16_SUB(pos->v[1].x, pos->v[0].x);
  fp16_t dy20 = BORG_FP16_SUB(pos->v[2].y, pos->v[0].y);
  fp16_t dx20 = BORG_FP16_SUB(pos->v[2].x, pos->v[0].x);
  fp16_t dy10 = BORG_FP16_SUB(pos->v[1].y, pos->v[0].y);
  fp16_t area = BORG_FP16_SUB(borg_fp16_mul(dx10, dy20),
                               borg_fp16_mul(dx20, dy10));
  if (fp16_ge_zero(area)) return 0;  // degenerate or back-facing

  // Hardware fstep.s expects positive edge values. 
  // Since we allow negative area, we negate it here and in the edge constants.
  area ^= 0x8000;
  *inv_area = borg_fp16_rcp(area);
  return 1;
}

// Rasterize a single triangle from 3 clip vertices (post-clipping).
static void rasterize_clipped_triangle(const clip_vertex_t *cv,
                                       const texture_t *t, int frame) {
  fp16_t ndc[3][3];
  triangle_t tri;
  perspective_divide(cv, ndc, &tri.screen_pos);
  fp16_t inv_area;
  int setup_res = triangle_setup(&tri.screen_pos, &inv_area);

  if (!setup_res) return;
  tri.inv_area = inv_area;

  compute_edge_vectors(tri.screen_pos.v, tri.edges.v);

  for (int v = 0; v < 3; v++) {
    tri.colors.v[v] = (rgb16_t){ cv[v].r, cv[v].g, cv[v].b };
    tri.uvs.v[v]    = (uv16_t){ cv[v].u, cv[v].v };
  }
  tri.z_vals  = (fp16x3_t){{ ndc[0][2], ndc[1][2], ndc[2][2] }};
  tri.has_uvs = (t->psram_offset >= 0);

  borg_load_spirb_shader_at(&rast_shader, BORG_IMEM_RAST_OFFSET);
  borg_load_spirb_shader_at(&frag_shader, BORG_IMEM_FRAG_OFFSET);
  borg_load_add_shader();

  shade_tiles(&tri, t, frame);
}

// Build clip-space vertices from vertex shader output and original attributes.
static void build_clip_vertices(const fp16_t *vout, int stride,
                                const borg_vertex_t vertices[3],
                                clip_vertex_t clip_in[3]) {
  for (int v = 0; v < 3; v++) {
    clip_in[v].x = vout[v * stride + 0];
    clip_in[v].y = vout[v * stride + 1];
    clip_in[v].z = (stride >= 3) ? vout[v * stride + 2] : FP16_ZERO;
    clip_in[v].w = (stride >= 4) ? vout[v * stride + 3] : FP16_ONE;
    clip_in[v].r = vertices[v].color[0];
    clip_in[v].g = vertices[v].color[1];
    clip_in[v].b = vertices[v].color[2];
    clip_in[v].u = vertices[v].uv[0];
    clip_in[v].v = vertices[v].uv[1];
  }
}

static void clip_and_rasterize(const clip_vertex_t clip_in[3],
                               const texture_t *t, int frame) {
  clip_vertex_t clip_a[MAX_CLIP_VERTS + 1];
  clip_vertex_t clip_b[MAX_CLIP_VERTS + 2];
  
  int n_near = clip_near(clip_in, 3, clip_a);
  if (n_near < 3) return;

  int n_far = clip_far(clip_a, n_near, clip_b);
  if (n_far < 3) return;

  PSRAM_OUT(5000) = 0x1111;
  PSRAM_OUT(5001) = n_near;
  PSRAM_OUT(5002) = n_far;

  for (int i = 1; i < n_far - 1; i++) {
    clip_vertex_t tri[3] = { clip_b[0], clip_b[i], clip_b[i + 1] };
    rasterize_clipped_triangle(tri, t, frame);
  }
}

void borgCmdDraw(const borg_draw_data_t *d, const borg_vertex_t vertices[3],
                 int frame) {
  unsigned int t_start = get_cycles();
  PSRAM_OUT(frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE) = 0;

  fp16_t attrs[NUM_VERTICES * 3];
  for (int v = 0; v < NUM_VERTICES; v++) {
    attrs[v * 3 + 0] = vertices[v].pos[0];
    attrs[v * 3 + 1] = vertices[v].pos[1];
    attrs[v * 3 + 2] = vertices[v].pos[2];
  }

  fp16_t vout[NUM_VERTICES * SPIRB_MAX_REGS];
  run_vertex_shader(d->uniforms, attrs, vout);

  clip_vertex_t clip_in[3];
  build_clip_vertices(vout, vert_shader.num_outputs, vertices, clip_in);

  clip_and_rasterize(clip_in, &tex, frame);
  t_draw_cycles += get_cycles() - t_start;
}

void borg_present(int frame) {
  // Wait for the GPU to finish the last draw command before finalizing the
  // frame!
  unsigned int t_wait = get_cycles();
  while (!(BORG_GPU->status & STATUS_REG_T__IDLE_bm))
    ;
  t_draw_cycles += get_cycles() - t_wait;

  int base = frame * FRAME_STRIDE + FRAME_FB_SIZE + FRAME_ZB_SIZE;
  PSRAM_OUT(base) = DONE_MARKER;
  PSRAM_OUT(base + 1) = t_init_cycles & 0xFFFF;
  PSRAM_OUT(base + 2) = (t_init_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 3) = t_clear_cycles & 0xFFFF;
  PSRAM_OUT(base + 4) = (t_clear_cycles >> 16) & 0xFFFF;
  PSRAM_OUT(base + 5) = t_draw_cycles & 0xFFFF;
  PSRAM_OUT(base + 6) = (t_draw_cycles >> 16) & 0xFFFF;
}
