# Auto-generated by MmioMap.scala — do not edit manually

# PSRAM addresses (QSPI/SPI space)
PSRAM_IO_SPI_ADDR = 0x001000
PSRAM_OUT_OFFSET = 128

# Shared layout constants
TEX_PSRAM_OFFSET = 4200
DONE_MARKER = 0xDEAD

# System clock (from MmioMap.scala)
CLOCK_MHZ = 4
FPGA_CLOCK_HZ = 4000000  # CLOCK_MHZ * 1e6

# User peripheral addressing (for TinyQV bus driver)
USER_PERIPHERAL_STRIDE = 0x100

# SoC peripheral offsets (tp-relative, bypass user peripheral decoding)
SOC_PERI_ID           = 0x08
SOC_PERI_GPIO_OUT_SEL = 0x0C
SOC_PERI_DEBUG_UART   = 0x18
SOC_PERI_TIME_LIMIT   = 0x2C

# User peripheral base offsets (tp-relative)
GPIO_BASE = 0x100
UART_BASE = 0x200
BORG_USER_BASE = 0x300

# GPIO sub-register offsets (relative to GPIO_BASE)
GPIO_OUT      = GPIO_BASE + 0
GPIO_IN       = GPIO_BASE + 4
GPIO_FUNC_SEL = GPIO_BASE + 0x20  # func_sel register space

# UART sub-register offsets (relative to UART_BASE)
UART_TX_DATA = UART_BASE + 0
UART_STATUS  = UART_BASE + 4

# Borg GPU sub-register offsets
BORG_IMEM_OFFSET = 128
BORG_CONTROL_OFFSET = 252
