# Auto-generated by MmioMap.scala — do not edit manually

# PSRAM addresses (QSPI/SPI space)
PSRAM_IO_SPI_ADDR = 0x001000
PSRAM_OUT_OFFSET = 128

# Shared layout constants
TEX_PSRAM_OFFSET = 4200
DONE_MARKER = 0xDEAD

# System clock (from MmioMap.scala)
CLOCK_MHZ = 4
FPGA_CLOCK_HZ = 4000000  # CLOCK_MHZ * 1e6

# User peripheral addressing (for TinyQV bus driver)
USER_PERIPHERAL_STRIDE = 0x80

# Borg GPU sub-register offsets
BORG_IMEM_OFFSET = 64
BORG_CONTROL_OFFSET = 124
