name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: determinate-systems/nix-installer-action@v16

      - name: Magic Nix Cache
        uses: determinate-systems/magic-nix-cache-action@v8

      - name: Generate SystemVerilog
        run: make generate_verilog

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp26a
