name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate SystemVerilog
        run: nix develop --command make generate_verilog

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@ttihp26a
