name: gds
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      pdk:
        description: 'PDK to build for'
        required: true
        default: 'sky130A'
        type: choice
        options:
          - sky130A
          - ihp-sg13g2

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate SystemVerilog
        run: nix develop --command make generate_verilog

      - name: Build GDS (Sky130)
        if: ${{ github.event.inputs.pdk == 'sky130A' || github.event_name != 'workflow_dispatch' }}
        uses: TinyTapeout/tt-gds-action@ttsky26a
        with:
          pdk: sky130A

      - name: Build GDS (IHP)
        if: ${{ github.event.inputs.pdk == 'ihp-sg13g2' }}
        uses: TinyTapeout/tt-gds-action@ttihp26a
        with:
          pdk: ihp-sg13g2

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck (Sky130)
        if: ${{ github.event.inputs.pdk == 'sky130A' || github.event_name != 'workflow_dispatch' }}
        uses: TinyTapeout/tt-gds-action/precheck@ttsky26a

      - name: Run Tiny Tapeout Precheck (IHP)
        if: ${{ github.event.inputs.pdk == 'ihp-sg13g2' }}
        uses: TinyTapeout/tt-gds-action/precheck@ttihp26a

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate SystemVerilog
        run: nix develop --command make generate_verilog

      - name: GL test (Sky130)
        if: ${{ github.event.inputs.pdk == 'sky130A' || github.event_name != 'workflow_dispatch' }}
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky26a
        env:
          CLOCK_MHZ: 4

      - name: GL test (IHP)
        if: ${{ github.event.inputs.pdk == 'ihp-sg13g2' }}
        uses: TinyTapeout/tt-gds-action/gl_test@ttihp26a
        env:
          CLOCK_MHZ: 4

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Viewer (Sky130)
        if: ${{ github.event.inputs.pdk == 'sky130A' || github.event_name != 'workflow_dispatch' }}
        uses: TinyTapeout/tt-gds-action/viewer@ttsky26a

      - name: Viewer (IHP)
        if: ${{ github.event.inputs.pdk == 'ihp-sg13g2' }}
        uses: TinyTapeout/tt-gds-action/viewer@ttihp26a
