name: test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: [self-hosted, gonsolo-workstation]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run tests
        run: |
          nix develop --command make test-all
        env:
          MILL_JOBS: 4

      - name: Upload test logs
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-logs
          path: test_logs/latest/

      - name: Upload waveform and cocotb results
        if: success() || failure()
        uses: actions/upload-artifact@v7
        with:
          name: cocotb-results
          path: |
            test/soc/sim_build/rtl/tb.fst
            test/soc/results.xml
            test/soc/sim_build/rtl/*.log
