name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        test: [core, borg]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run tests
        run: |
          nix develop --command make test-cocotb-soc-${{ matrix.test }}-rtl

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/soc/results.xml"
        if: always()

      - name: upload waveform and test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test }}
          path: |
            test/soc/sim_build/rtl/tb.fst
            test/soc/results.xml
            test/soc/sim_build/rtl/*.log

